// Validate the whole list before changing any rack; keep pallet IDs as strings.
function bulkPalletNumbers(value,count){
  const raw=String(value??'').trim();
  WMS.assert(Number.isInteger(count)&&count>0&&count<=100,'Pilih 1–100 rak terlebih dahulu.');
  if(raw.includes(',')){
    const values=raw.split(',').map(v=>v.trim());
    WMS.assert(values.every(v=>/^[0-9]{1,20}$/.test(v)),'Isi nomor pallet berupa angka, dipisahkan koma. Jangan sisakan nomor kosong.');
    WMS.assert(values.length===count,'Ada '+values.length+' nomor pallet untuk '+count+' rak. Jumlahnya harus sama.');
    return values.map(WMS.pallet);
  }
  WMS.assert(/^[0-9]{1,15}$/.test(raw),'Isi satu nomor awal, atau daftar nomor yang dipisahkan koma.');
  const start=Number(raw);WMS.assert(Number.isSafeInteger(start+count-1),'Nomor berurutan terlalu besar.');
  return Array.from({length:count},(_,n)=>String(start+n));
}
function bulkSelectionBar(){return `<div class="selection-bar"><span>${S.emptySelected?.size||0} rak kosong dipilih</span><div class="row">${btn('Lanjut input','bulk-next','small')}${btn('Batal','bulk-stop','small')}</div></div>`;}
function beginBulk(){S.bulkSelecting=true;S.emptySelected=new Set();S.selecting=false;S.selected.clear();S.search='';S.filter='all';S.productFilters={};render();toast('Pilih rak kosong, lalu Lanjut input.');}
function toggleEmptySlot(id){const loc=locs().find(l=>l.id===id&&l.kind==='rack');if(!loc||stockAt(id).length)return toast('Hanya rak kosong yang bisa dipilih.');if(S.emptySelected.has(id))S.emptySelected.delete(id);else {if(S.emptySelected.size>=100)return toast('Maksimal 100 rak per transaksi.');S.emptySelected.add(id);}updateSelectionUI();}
function openBulkInput(){
  if(!S.emptySelected?.size)return toast('Pilih minimal satu rak kosong.');
  const ids=[...S.emptySelected],old=S.bulkDraft;
  const item=old?.room===S.room?old.item:freshItem();
  S.bulkDraft={room:S.room,item,defaultQty:old?.room===S.room?old.defaultQty:item.qty,sequence:'',rows:locs().filter(l=>ids.includes(l.id)).sort((a,b)=>a.order-b.order).map(l=>old?.room===S.room&&old.rows.find(r=>r.locationId===l.id)||{locationId:l.id,qty:item.qty,palletNo:''})};
  nav('bulkInput');
}
function bulkRows(){return S.bulkDraft.rows.map((r,n)=>{const loc=S.data.locations.find(l=>l.id===r.locationId);return `<div class="bulk-row"><strong>${esc(loc.display)}${loc.functionType!==WMS.FUNCTIONS[0]?'<small>Non-komersial</small>':''}</strong><label>No. Pallet<input class="field" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="20" autocomplete="off" data-bulk-row="${n}" data-bulk-field="palletNo" aria-label="No. Pallet ${esc(loc.display)}" placeholder="31" value="${esc(r.palletNo)}"></label><label>Jumlah (CTN)<input class="field" type="number" min="1" max="1000000" step="1" inputmode="numeric" data-bulk-row="${n}" data-bulk-field="qty" aria-label="Jumlah ${esc(loc.display)}" value="${esc(r.qty)}"></label></div>`;}).join('');}
function bulkSummary(){const d=S.bulkDraft,total=d.rows.reduce((n,r)=>n+(Number(r.qty)||0),0);return `${d.rows.length} rak · ${d.rows.length} item/pallet · ${number(total)} CTN`;}
function bulkInputView(){const d=S.bulkDraft,i=d.item;return `${sessionBar()}<div class="intro-line"><div><span class="eyebrow">PENERIMAAN BARANG</span><h1>Isi banyak rak</h1><p class="sub">${esc(d.room)} · Detail barang sama, nomor pallet dan jumlah per rak bisa berbeda.</p></div>${btn('Ubah pilihan rak','bulk-back','','back')}</div><div id="action-error"></div><div class="panel workflow-panel"><h2>1. Detail bersama</h2><div class="two-col"><label class="label">Produk<select class="field" data-bulk-common="sku" aria-label="Produk bersama">${opts(S.data.skus.filter(s=>s.group===S.mode).map(s=>s.code),i.sku)}</select></label><label class="label">KP<input class="field" type="date" data-bulk-common="kp" aria-label="KP bersama" value="${esc(i.kp)}"></label><label class="label">Status<select class="field" data-bulk-common="status" aria-label="Status bersama">${opts(WMS.STATUS,i.status)}</select></label>${S.mode==='CSFG'?`<label class="label">Kode SPV *<select class="field" data-bulk-common="spv" aria-label="SPV bersama"><option value="">Pilih SPV</option>${opts(['JT','HW','AK','-'],i.spv)}</select></label>`:''}</div><label class="label">Catatan<input class="field" maxlength="500" data-bulk-common="note" aria-label="Catatan bersama" placeholder="Contoh: Retur dari Distributor A, kemasan rusak" value="${esc(i.note)}"></label><p class="notice">Barang retur memakai status biasa. Pengirim dan alasan retur dicatat di catatan.</p></div><div class="panel workflow-panel"><h2>2. Rincian per rak</h2><p class="sub">Satuan CTN. Nomor pallet boleh 31, 125, atau 999; tanpa nol di depan.</p><div class="bulk-tools"><label class="label">Jumlah untuk semua rak<input id="bulk-default" class="field" type="number" min="1" max="1000000" step="1" inputmode="numeric" value="${esc(d.defaultQty)}"></label>${btn('Terapkan jumlah','bulk-qty')}<label class="label">Nomor pallet (awal / daftar)<input id="bulk-sequence" class="field" type="text" inputmode="text" maxlength="2200" autocomplete="off" spellcheck="false" aria-describedby="bulk-pallet-help" placeholder="31 atau 99, 11, 37" value="${esc(d.sequence)}"></label>${btn('Terapkan nomor pallet','bulk-sequence')}</div><p class="notice" id="bulk-pallet-help">Satu angka (31) mengisi nomor berurutan: 31, 32, 33. Untuk nomor manual, pisahkan dengan koma: 99, 11, 37 atau 99,11,37. Jumlah nomor harus sama dengan jumlah rak terpilih. Nomor diterapkan sesuai urutan rak di bawah dan tiap baris tetap bisa diedit.</p><div id="bulk-rows">${bulkRows()}</div></div><div class="workflow-save"><strong id="bulk-summary">${bulkSummary()}</strong>${btn('Tinjau & simpan','bulk-review','primary','check')}</div>`;}
function bulkRequest(){const d=S.bulkDraft;return {action:'bulkReceive',version:S.data.version,item:{...d.item},rows:d.rows.map(r=>({...r}))};}
function reviewBulk(){try{const req=bulkRequest();Delivery.mutate(S.data,req,S.session,uid,new Date().toISOString());S.bulkConfirm=req;openModal('Simpan ke rak terpilih?',esc(S.bulkDraft.room),`<div id="action-error"></div><p class="sub">${esc(S.bulkDraft.item.sku)} · KP ${esc(S.bulkDraft.item.kp)} · ${esc(S.bulkDraft.item.status)}${S.mode==='CSFG'?' · SPV '+esc(S.bulkDraft.item.spv):''}</p><p><strong>${bulkSummary()}</strong></p>${S.bulkDraft.item.note?'<p class="notice">'+esc(S.bulkDraft.item.note)+'</p>':''}<div class="bulk-review-list">${req.rows.map(r=>`<p>${esc(S.data.locations.find(l=>l.id===r.locationId).display)} · Pallet ${esc(WMS.pallet(r.palletNo)||'—')} · ${esc(r.qty)} CTN</p>`).join('')}</div><p class="notice">Seluruh rak disimpan bersama${gas?' di HP. Tekan SYNC saat koneksi tersedia':''}.</p>`,`${btn('Kembali','close-modal')}${btn('SAVE semua rak','bulk-save','primary','check')}`);}catch(e){storageError(e);}}
document.addEventListener('input',e=>{if(!S.bulkDraft)return;const el=e.target;if(el.dataset.bulkCommon)S.bulkDraft.item[el.dataset.bulkCommon]=el.value;if(el.dataset.bulkField){S.bulkDraft.rows[Number(el.dataset.bulkRow)][el.dataset.bulkField]=el.value;$('#bulk-summary').textContent=bulkSummary();}if(el.id==='bulk-default')S.bulkDraft.defaultQty=el.value;if(el.id==='bulk-sequence')S.bulkDraft.sequence=el.value;});
document.addEventListener('change',e=>{if(e.target.dataset.bulkCommon&&S.bulkDraft)S.bulkDraft.item[e.target.dataset.bulkCommon]=e.target.value;});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||S.busy)return;switch(b.dataset.action){
  case 'bulk-start':beginBulk();break;
  case 'bulk-stop':S.bulkSelecting=false;S.emptySelected=new Set();render();break;
  case 'bulk-next':openBulkInput();break;
  case 'bulk-back':{const ids=S.bulkDraft.rows.map(r=>r.locationId);if(!Navigation.allowLeave())return;nav('storage');S.rackSelection=true;S.rackSelected=new Set(ids);render();break;}
  case 'bulk-qty':{const qty=Number(S.bulkDraft.defaultQty);if(!Number.isInteger(qty)||qty<1||qty>1000000)return toast('Jumlah harus 1–1.000.000 CTN.');S.bulkDraft.rows.forEach(r=>r.qty=qty);$('#bulk-rows').innerHTML=bulkRows();$('#bulk-summary').textContent=bulkSummary();break;}
  case 'bulk-sequence':{try{const values=bulkPalletNumbers(S.bulkDraft.sequence,S.bulkDraft.rows.length);S.bulkDraft.rows.forEach((r,k)=>r.palletNo=values[k]);S.formDirty=true;$('#bulk-rows').innerHTML=bulkRows();toast('Nomor pallet diterapkan ke '+values.length+' rak. Periksa rincian sebelum menyimpan.');}catch(error){toast(errorText(error));}break;}
  case 'bulk-review':reviewBulk();break;
  case 'bulk-save':if(S.bulkConfirm&&await mutate(S.bulkConfirm)){closeModal();S.bulkDraft=null;S.bulkConfirm=null;S.emptySelected=new Set();nav('storage');toast('Semua rak tersimpan'+(gas?' di HP · Menunggu SYNC.':'.'));}break;
}});
