const deliveryLabel=state=>({DRAFT:'Draft / picklist',ISSUED:'Barang keluar',CANCELLED:'Dibatalkan'}[state]||state);
function deliveryPending(id){if(!gas)return false;try{return storedOffline()?.queue.some(op=>op.request.documentId===id)||false;}catch{return false;}}

function deliveryTotal(d){return ['CTN','PACK'].map(u=>[u,d.lines.filter(l=>l.unit===u).reduce((n,l)=>n+Number(l.qty),0)]).filter(([,n])=>n).map(([u,n])=>number(n)+' '+u).join(' · ');}
function openDeliveryDraft(id,ids=[]){
  if(!S.session)return toast('Mulai sesi terlebih dahulu.');const d=id?Delivery.find(S.data,id):null;if(id&&(!d||d.mode!==S.mode||d.state!=='DRAFT'))return toast('Draft tidak tersedia. Muat ulang.');
  if(!Navigation.allowLeave())return;closeModal();S.editor=null;if(!id&&!ids.length&&S.dnDraft?.mode===S.mode){renderDeliveryDraft();return;}S.dnDraft=d?JSON.parse(JSON.stringify(d)):{id:uid(),mode:S.mode,revision:0,date:S.session.date,shift:S.session.shift,truck:'',destination:'',note:'',lines:ids.map(itemId=>({itemId,qty:Delivery.availability(S.data,itemId).available})).filter(l=>l.qty>0)};if(!S.dnDraft.shift)S.dnDraft.shift=S.session.shift;S.pickSummaryOpen=true;S.dnDraftSearch='';S.dnProduct='';renderDeliveryDraft();
}
function capitalizeTruckInput(el){
 if(!el)return;const before=el.value,after=before.toUpperCase();if(before===after)return;
 const start=el.selectionStart,end=el.selectionEnd,direction=el.selectionDirection;el.value=after;
 if(typeof start==='number'&&typeof end==='number')el.setSelectionRange(before.slice(0,start).toUpperCase().length,before.slice(0,end).toUpperCase().length,direction||'none');
}
function readDeliveryDraft(){const d=S.dnDraft;if(!d)return;for(const k of ['date','shift','truck','destination','note'])if($('#dn-'+k)){const value=$('#dn-'+k).value;d[k]=k==='truck'?value.toUpperCase():value;}}
function pickDetails(i,loc){return `<strong>${esc(i.sku)}</strong><span>${esc(loc.room)} / ${esc(loc.display)} · KP ${kpMarkup(i.kp)}</span><span>Pallet ${esc(Pallets.label(i)||'—')+(i.palletId?' · Asal P '+esc(i.palletNo):'')}${S.mode==='CSFG'?' · SPV '+esc(i.spv):''} · <b class="${i.status==='Release'?'':'pick-caution'}">${esc(i.status)}</b></span>${i.note?'<span>'+esc(i.note)+'</span>':''}`;}
function reservationMarkup(i,a){return '<span class="pick-availability">Stok fisik <b>'+number(a.physical)+' '+esc(i.unit)+'</b> · Tersedia untuk picking <b>'+number(a.available)+' '+esc(i.unit)+'</b></span>'+(a.reserved?'<span class="reservation-badge">'+(a.available?'Sudah masuk picking':'Dialokasikan penuh')+' · '+number(a.reserved)+' '+esc(i.unit)+'</span>':'')+a.allocations.map(x=>'<span class="reservation-detail">'+esc(x.truck)+' · '+esc(x.number)+' · '+number(x.qty)+' '+esc(i.unit)+'</span>').join('');}
function deliveryPicker(){const selected=new Set(S.dnDraft.lines.map(l=>l.itemId)),index=new Map(locs(null).map(l=>[l.id,l])),reserved=Delivery.reservationIndex(S.data,S.dnDraft.id);
 const items=Picking.candidates(S.data,S.mode,{query:S.dnDraftSearch||'',sku:S.dnProduct||'',fefo:!!S.dnFefo});
 return items.map(i=>{const a=Delivery.availability(S.data,i.id,S.dnDraft.id,reserved),chosen=selected.has(i.id);return '<label class="dn-pick-row '+(chosen?'picked':'')+' '+(!a.available?'fully-reserved':'')+'"><input type="checkbox" class="check" data-dn-item="'+esc(i.id)+'" aria-label="Ambil '+esc(i.sku)+' '+esc(index.get(i.locationId).room)+' '+esc(index.get(i.locationId).display)+'" '+(chosen?'checked':'')+' '+(!a.available&&!chosen?'disabled':'')+'><span class="grow">'+pickDetails(i,index.get(i.locationId))+reservationMarkup(i,a)+'</span></label>';}).join('')||'<p class="notice">Tidak ada stok yang cocok.</p>';
}

function updatePickedList(){if($('#dn-picked-list'))$('#dn-picked-list').innerHTML=pickedList();updatePickSummary();}
function renderDeliveryDraft(){nav('picking');}
function pickingView(){const d=S.dnDraft;return `${sessionBar()}${workNavigation()}<div class="intro-line"><div><span class="eyebrow">PICKLIST & BARANG KELUAR</span><h1>${d.revision?'Edit picking list':'Buat picking list'}</h1><p class="sub">Pilih barang, cek rincian pallet, lalu simpan draft. Stok berkurang saat Konfirmasi barang keluar.</p></div>${btn('Daftar Picking List','pl-home','','back')}</div><div id="action-error"></div><div class="picking-layout"><section class="panel workflow-panel"><h2>1. Pilih barang</h2><label class="label" for="dn-product">Produk</label><select class="field" id="dn-product"><option value="">Semua produk</option>${opts(S.data.skus.filter(s=>s.group===S.mode).map(s=>s.code),S.dnProduct||'')}</select><label class="label" for="dn-pick-search">Cari stok</label><input class="field" id="dn-pick-search" value="${esc(S.dnDraftSearch||'')}" placeholder="KP, lokasi, pallet, SPV, atau status"><div class="inventory-actions">${btn('FEFO Pick','dn-fefo',S.dnFefo?'primary':'','layers',`aria-pressed="${!!S.dnFefo}"`)}${btn('Lihat terpilih','dn-picked')}</div><p class="notice">${S.dnFefo?'Prioritas pengambilan berdasarkan KP tertua. Release didahulukan per produk. Status lainnya tetap terlihat untuk diperiksa.':'Aktifkan FEFO Pick untuk mengurutkan berdasarkan KP tertua. Pilih pallet dan jumlah secara manual.'}</p><div class="dn-picker" id="dn-picker">${deliveryPicker()}</div></section><section class="panel workflow-panel" id="picked-panel"><h2>2. Picking list terpilih</h2><p class="notice" id="dn-selected-count">${pickSummary()}</p><div id="dn-picked-list" class="dn-selected-list">${pickedList()}</div><p class="notice">Maksimal 100 item. Menghapus pilihan tidak menghapus stok.</p></section></div><section class="panel workflow-panel"><h2>3. Detail muatan truk</h2><div class="two-col"><label class="label">Truk / nomor polisi<input id="dn-truck" class="field" maxlength="80" autocapitalize="characters" spellcheck="false" placeholder="Contoh: B 1234 AB / Truk 1" value="${esc((d.truck||'').toUpperCase())}"></label><label class="label">Shift<select id="dn-shift" class="field">${opts(['S1','S2','S3'],d.shift)}</select></label><label class="label">Tanggal<input type="date" id="dn-date" class="field" value="${esc(d.date)}"></label><label class="label">Tujuan / penerima<input id="dn-destination" class="field" maxlength="120" placeholder="Contoh: Packing / Bapak Andi" value="${esc(d.destination)}"></label></div><label class="label" for="dn-note">Catatan</label><input id="dn-note" class="field" maxlength="500" value="${esc(d.note)}" placeholder="Nomor order, kendaraan, atau keperluan"><p class="notice">Tekan Simpan draft agar pilihan tersimpan di perangkat. Draft mencadangkan jumlah di HP ini, termasuk saat offline. Jumlah awal mengikuti sisa tersedia dan boleh diubah. Stok fisik berkurang saat Konfirmasi Barang Keluar setelah No. SJ SAP tersedia.</p></section><div class="workflow-save picking-bottom" id="pick-bottom-bar">${pickBar()}</div>`;}

async function saveDeliveryDraft(){readDeliveryDraft();const d=S.dnDraft;if(!d)return;if(await mutate({action:'saveDelivery',documentId:d.id,documentRevision:d.revision,date:d.date,shift:d.shift,truck:d.truck||'',destination:d.destination,note:d.note,lines:d.lines.map(l=>({itemId:l.itemId,qty:l.qty}))})){closeModal();S.dnDraft=null;S.selected.clear();S.pickListFilters={date:d.date,shift:d.shift};viewDelivery(d.id,'picking');toast('Draft tersimpan'+(gas?' di HP · Tekan SYNC untuk membagikan ke tim.':'.'));}}
function viewDelivery(id,kind='picking'){const d=Delivery.find(S.data,id);if(!d||d.mode!==S.mode)return toast('Dokumen tidak ditemukan. Muat ulang.');closeModal();S.editor=null;if(kind==='delivery'&&d.state!=='ISSUED')return toast('Picking list belum dikonfirmasi keluar.');S.dnViewing=id;S.documentKind=kind;nav('deliveryDetail');}


async function commitDelivery(){const c=S.dnConfirm;if(!c)return;let sjNumber;if(c.action==='issueDelivery'){try{sjNumber=Delivery.suratJalan($('#dn-sj')?.value||'');c.sjNumber=sjNumber;}catch(err){const el=$('#action-error');if(el)el.textContent=err.message;$('#dn-sj')?.focus();return;}}if(await mutate({action:c.action,documentId:c.id,documentRevision:c.revision,...(sjNumber?{sjNumber}:{})})){closeModal();S.dnConfirm=null;S.selected.clear();viewDelivery(c.id,c.action==='issueDelivery'?'delivery':'picking');toast(c.action==='issueDelivery'?'Barang keluar dicatat dan stok diperbarui'+(gas?' di HP · Menunggu SYNC.':'.'):'Draft dibatalkan.');}}
function downloadDelivery(){const d=Delivery.find(S.data,S.dnViewing);if(!d)return;const link=document.createElement('a'),url=URL.createObjectURL(new Blob([documentText(d)],{type:'text/plain;charset=utf-8'}));link.href=url;link.download=(S.documentKind==='delivery'?(d.sjNumber||d.number):pickingNumber(d)).replace(/[^A-Za-z0-9._-]/g,'_')+'.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copyDelivery(){const d=Delivery.find(S.data,S.dnViewing);if(!d)return;try{await navigator.clipboard.writeText(documentText(d));toast('Dokumen disalin.');}catch{const el=$('#dn-text');const details=el.closest('details');if(details)details.open=true;el.focus();el.select();toast('Teks dipilih. Gunakan Salin pada perangkat.');}}

document.addEventListener('input',e=>{if(e.target.id==='dn-truck'&&!e.isComposing)capitalizeTruckInput(e.target);if(['dn-date','dn-shift','dn-truck','dn-destination','dn-note'].includes(e.target.id))readDeliveryDraft();if(e.target.id==='dn-pick-search'){readDeliveryDraft();S.dnDraftSearch=e.target.value;$('#dn-picker').innerHTML=deliveryPicker();}if(e.target.dataset.dnQty){const l=S.dnDraft?.lines.find(l=>l.itemId===e.target.dataset.dnQty);if(l){l.qty=e.target.value;updatePickSummary();}}if(e.target.id==='dn-search'){S.deliverySearch=e.target.value;clearTimeout(S.dnSearchTimer);S.dnSearchTimer=setTimeout(()=>{const start=$('#dn-search')?.selectionStart;render();const el=$('#dn-search');el?.focus();el?.setSelectionRange(start,start);},180);}});
document.addEventListener('change',e=>{if(e.target.id==='dn-shift')readDeliveryDraft();if(e.target.id==='dn-product'){S.dnProduct=e.target.value;$('#dn-picker').innerHTML=deliveryPicker();}if(e.target.dataset.dnItem){readDeliveryDraft();const id=e.target.dataset.dnItem;S.dnDraft.lines=S.dnDraft.lines.filter(l=>l.itemId!==id);if(e.target.checked&&S.dnDraft.lines.length>=100){e.target.checked=false;toast('Maksimal 100 item untuk picklist.');return;}if(e.target.checked){const qty=Delivery.availability(S.data,id,S.dnDraft.id).available;if(qty>0)S.dnDraft.lines.push({itemId:id,qty});else {e.target.checked=false;toast('Jumlah sudah dialokasikan penuh ke picking lain.');}}$('#dn-picker').innerHTML=deliveryPicker();updatePickedList();}if(e.target.id==='dn-status'){S.deliveryFilter=e.target.value;render();}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||S.busy)return;switch(b.dataset.action){case 'dn-fefo':S.dnFefo=!S.dnFefo;render();break;case 'dn-picked':$('#picked-panel')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});break;case 'dn-remove':S.formDirty=true;S.dnDraft.lines=S.dnDraft.lines.filter(l=>l.itemId!==b.dataset.id);$('#dn-picker').innerHTML=deliveryPicker();updatePickedList();break;case 'dn-home':if(!S.session)return toast('Mulai sesi terlebih dahulu.');nav('delivery');break;case 'dn-new':openDeliveryDraft(null,[...S.selected]);break;case 'dn-view':viewDelivery(b.dataset.id,'delivery');break;case 'dn-edit':openDeliveryDraft(S.dnViewing);break;case 'dn-save':await saveDeliveryDraft();break;case 'dn-issue':deliveryConfirm('issueDelivery');break;case 'dn-cancel':deliveryConfirm('cancelDelivery');break;case 'dn-confirm':await commitDelivery();break;case 'dn-back':viewDelivery(S.dnViewing);break;case 'dn-download':downloadDelivery();break;case 'dn-copy':await copyDelivery();break;case 'dn-print':printDelivery();break;}});

document.addEventListener('compositionend',e=>{if(e.target.id==='dn-truck'){capitalizeTruckInput(e.target);readDeliveryDraft();}});
