/* Dedicated transaction exports; the daily WhatsApp stock report is unchanged. */
function exportDashboardCard(){return `<section class="panel report-banner export-banner"><div class="report-icon">${icon('report',24)}</div><div class="grow"><h3>Ekspor Excel</h3><p>Riwayat barang masuk dan keluar untuk kartu stok.</p></div>${btn('Buka Ekspor','export-open','','download')}</section>`;}
function exportState(){if(!S.excel||S.excel.mode!==S.mode)S.excel={mode:S.mode,type:'IN',from:S.session.date,to:S.session.date,shift:S.session.shift,room:'',header:false,result:null,loading:false,error:''};return S.excel;}
function exportView(){const x=exportState();return `${sessionBar()}${workNavigation()}<div class="intro-line"><div><span class="eyebrow">KARTU STOK · ${esc(S.mode)}</span><h1>Ekspor Excel</h1><p class="sub">Salin transaksi ke Excel. Laporan WhatsApp tetap untuk posisi stok saat ini.</p></div>${btn('Muat riwayat terbaru','export-load','','refresh')}</div><div class="export-tabs" role="tablist" aria-label="Jenis transaksi">${['IN','OUT','KOREKSI'].map(t=>`<button class="btn ${x.type===t?'primary':''}" role="tab" aria-selected="${x.type===t}" data-action="export-tab" data-type="${t}">${t==='IN'?'IN · Barang masuk':t==='OUT'?'OUT · Barang keluar':'Koreksi data'}</button>`).join('')}</div><section class="panel export-panel"><div class="export-filters"><label>Dari tanggal<input class="field" type="date" data-export-field="from" value="${esc(x.from)}"></label><label>Sampai tanggal<input class="field" type="date" data-export-field="to" value="${esc(x.to)}"></label><label>Shift<select class="field" data-export-field="shift"><option value="">Semua shift</option>${opts(['S1','S2','S3'],x.shift)}</select></label><label>Ruangan<select class="field" data-export-field="room"><option value="">Seluruh ${esc(S.mode)}</option>${opts(rooms(),x.room)}</select></label></div><div class="export-options">${btn('Seluruh periode','export-all','small')}${btn('Shift aktif','export-current','small')}<label class="row"><input type="checkbox" data-export-field="header" ${x.header?'checked':''}> Sertakan header</label></div><p class="notice">Tanggal mengikuti tanggal operasional sesi penerimaan / konfirmasi keluar. IN merekam jumlah saat diterima, bukan saldo sekarang. OUT hanya barang keluar yang sudah dikonfirmasi.</p><p class="notice">Riwayat IN mulai dicatat oleh patch v1.5.7. Stok lama tidak dibuat menjadi penerimaan baru. Nomor pallet dan KP memakai data pada saat transaksi. Format v1.6.2 memuat ID Item asal dan No. SJ; gunakan template Excel v1.6.2. No. SJ hanya berisi nomor SAP yang diisi saat konfirmasi keluar. Dokumen lama tanpa SJ tetap kosong; nomor DN internal bukan nomor SAP.</p><div id="export-results">${exportResults()}</div></section>`;}
function exportSelection(){const x=exportState();return StockExport.select(x.result?.rows||[],S.mode,x);}
function exportResults(){const x=exportState(),pending=offlineCount();let rows=[];try{rows=exportSelection();}catch(e){return `<div class="error">${esc(errorText(e))}</div>`;}
 const problems=StockExport.issues(rows),blocked=!x.result||x.loading||!rows.length||problems.length||gas&&pending>0;
 const header=StockExport.headers[x.type],ctn=rows.filter(r=>r.unit==='CTN').reduce((n,r)=>n+Number(r.qty),0);
 return `${pending?`<div class="error">${pending} transaksi masih tersimpan di HP. Tekan SYNC, lalu muat riwayat terbaru sebelum menyalin laporan pusat. ${btn('SYNC','export-sync','small','refresh')}</div>`:''}${x.error?`<div class="error">${esc(x.error)}</div>`:''}${x.loading?'<p role="status">Memuat riwayat transaksi…</p>':''}${!x.result&&!x.loading?'<p class="notice">Tekan Muat riwayat terbaru untuk mengambil data.</p>':''}${x.result?`<div class="export-summary"><div><strong>${number(rows.length)} baris · ${number(ctn)} CTN</strong><p class="notice">${gas?'Data pusat':'Data pratinjau lokal'} dimuat ${esc(new Date(x.result.asOf).toLocaleString('id-ID'))}. ${navigator.onLine===false?'Offline — menampilkan data yang terakhir dimuat.':''}</p></div>${btn('Salin '+x.type+' untuk Excel','export-copy','primary','copy',blocked?'disabled':'')}</div>`:''}${rows.some(r=>r.identityRepaired)?'<p class="notice">Identitas laporan lama dipisahkan berdasarkan SKU. Gunakan file Excel v1.6.2 agar identitas IN/OUT cocok.</p>':''}${problems.length?`<div class="error">${problems.map(esc).join('<br>')}<br>Penyalinan diblokir agar kode dan satuan Excel tidak salah.</div>`:''}${rows.some(r=>r.type==='OUT'&&!r.sjNumber)?'<p class="notice">Ada pengeluaran lama tanpa No. SJ SAP. Cocokkan dengan dokumen admin; nomor DN internal tidak digunakan sebagai pengganti.</p>':''}${rows.some(r=>!r.shift)?'<p class="notice">Ada DN lama tanpa identitas shift konfirmasi. Shift dibiarkan kosong; jangan dianggap sebagai shift pembuatan picking.</p>':''}${x.result&&!rows.length?'<p class="activity-empty">Tidak ada transaksi yang cocok. Coba Seluruh periode atau periksa filter. Data sebelum pencatatan IN dimulai memang tidak tersedia.</p>':''}${rows.length?`<div class="export-table-wrap" tabindex="0" aria-label="Pratinjau transaksi, geser untuk melihat semua kolom"><table class="export-table"><thead><tr>${header.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,100).map(r=>`<tr>${StockExport.values(r).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="notice">Pratinjau ${Math.min(100,rows.length)} dari ${rows.length} baris. Tombol Salin mencakup seluruh hasil filter. Paste tanpa header di bawah header tabel INPUT_IN, INPUT_OUT, atau KOREKSI. Untuk template trial ini mulai A4. Hindari ID Trans duplikat. Kolom tersembunyi tetap ikut terisi. IN 14 kolom, OUT 18 kolom, KOREKSI 25 kolom. Ekspor koreksi terpisah; jangan menambahkan kembali IN lama. QTY dalam CTN. Format tanggal YYYY-MM-DD.</p><p class="notice">ID Trans tetap sama saat diekspor ulang. Copy-paste tidak menghapus duplikat otomatis: periksa ID sebelum menambah data. Ekspor seluruh periode digunakan untuk mengisi ulang tabel, bukan menambahkan transaksi yang sama.</p>`:''}`;
}
function refreshExportResults(){const el=$('#export-results');if(el)el.innerHTML=exportResults();}
async function loadExport(){const x=exportState();if(x.loading)return;x.loading=true;x.error='';refreshExportResults();try{
 let result;if(gas){WMS.assert(navigator.onLine!==false,'Perlu koneksi untuk memuat riwayat pusat.');result=await call('getStockExport',S.session.id);}
 else {const data=localData();result={schema:StockExport.schema,mode:S.mode,rows:StockExport.allRows(data.transactions||[],data.deliveryNotes||[],data.exportSessions||[],S.mode),asOf:new Date().toISOString()};}
 WMS.assert(result&&result.mode===x.mode&&Array.isArray(result.rows),'Data ekspor tidak sesuai gudang.');WMS.assert(result.schema===StockExport.schema,'Versi ekspor belum cocok. Update Index dan Code.gs dari paket v1.6.2, Deploy → New version, lalu buka ulang aplikasi.');x.result=result;
 }catch(e){x.error=/is not a function/.test(errorText(e))?'Fungsi ekspor belum tersedia pada deployment yang dibuka. Pastikan Index dan Code.gs berasal dari paket yang sama, lalu Deploy → New version dan buka ulang URL deployment itu. Ini bukan karena riwayat IN kosong.':errorText(e);x.result=null;}finally{x.loading=false;if(S.page==='exports'&&S.excel===x)refreshExportResults();}}
async function copyExport(){const x=exportState();try{
 WMS.assert(x.result&&!x.loading,'Muat riwayat terlebih dahulu.');WMS.assert(!gas||offlineCount()===0,'SYNC antrean HP dan muat riwayat terlebih dahulu.');WMS.assert(x.result.schema===StockExport.schema,'Muat ulang riwayat dari deployment v1.6.2 sebelum menyalin.');const rows=exportSelection();WMS.assert(rows.length,'Tidak ada transaksi untuk disalin.');const text=StockExport.tsv(rows,x.type,x.header);
 try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(text);toast(rows.length+' baris '+x.type+' disalin. Paste ke Excel.');}
 catch{openModal('Salin '+x.type+' untuk Excel','Pilih seluruh teks lalu salin. Kolom dipisahkan tab.',`<textarea id="export-copy-text" class="field" rows="12" readonly aria-label="Teks ekspor Excel">${esc(text)}</textarea>`,btn('Tutup','close-modal'));const el=$('#export-copy-text');el.focus();el.select();}
 }catch(e){toast(errorText(e));}}
document.addEventListener('change',e=>{const key=e.target.dataset.exportField;if(!key)return;const x=exportState();x[key]=key==='header'?e.target.checked:e.target.value;refreshExportResults();});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||S.busy)return;const a=b.dataset.action;if(!a.startsWith('export-'))return;
 if(a==='export-open'){if(!S.session)return;exportState();if(nav('exports'))await loadExport();}
 else if(a==='export-load')await loadExport();
 else if(a==='export-tab'){exportState().type=b.dataset.type;render();}
 else if(a==='export-all'){Object.assign(exportState(),{from:'',to:'',shift:''});render();}
 else if(a==='export-current'){Object.assign(exportState(),{from:S.session.date,to:S.session.date,shift:S.session.shift});render();}
 else if(a==='export-copy')await copyExport();
 else if(a==='export-sync'){const x=exportState();x.result=null;if(await syncOfflineData())await loadExport();}
});
