/* Full-room overview. Filters must match the SAME item, not different items in one rack. */
function inventoryItemMatches(i,loc){
  const f=S.productFilters||{},q=S.search.trim().toLowerCase();
  return (!q||`${loc.display} ${loc.room} ${i.sku} ${i.kp} ${WMS.short(i.kp)} ${i.qty} ${i.spv} ${i.palletNo||''} ${i.palletLabel||''} ${i.note}`.toLowerCase().includes(q))
    &&(!f.status||i.status===f.status)&&(!f.sku||i.sku===f.sku)&&(!f.kp||i.kp===f.kp)&&(!f.qty||i.qty===Number(f.qty))&&(!f.spv||i.spv===f.spv)
    &&(S.filter!=='Hold'||i.status==='Hold');
}
function inventoryLocationMatches(loc,items){
  if(S.filter==='empty'&&items.length)return false;
  if(S.filter==='filled'&&!items.length)return false;
  if(S.filter==='noncomm'&&loc.functionType===WMS.FUNCTIONS[0])return false;
  const f=S.productFilters||{},itemFilter=f.status||f.sku||f.kp||f.qty||f.spv||S.filter==='Hold';
  if(items.length)return items.some(i=>inventoryItemMatches(i,loc));
  return !itemFilter&&(!S.search.trim()||`${loc.display} ${loc.room}`.toLowerCase().includes(S.search.trim().toLowerCase()));
}
function stockDetailMarkup(i,loc,reservations){const allocation=Delivery.availability(S.data,i.id,null,reservations);return `<span class="rack-item ${inventoryItemMatches(i,loc)?'':'not-matched'}"><span class="rack-item-head"><strong>${esc(i.sku)}</strong><b>${number(i.qty)} ${esc(i.unit)}</b></span><span>KP ${kpMarkup(i.kp)}</span><span class="rack-item-tags">${S.mode==='CSFG'?`<span>SPV ${esc(i.spv)}</span>`:''}<span class="item-status ${i.status==='Hold'?'hold':''}">${esc(i.status)}</span></span>${i.palletNo?`<span>Pallet ${esc(WMS.pallet(i.palletNo))}</span>`:''}${allocation.reserved?`<span class="reservation-badge">Picking ${number(allocation.reserved)} · Tersedia ${number(allocation.available)} ${esc(i.unit)}</span>${allocation.overbooked?'<span class="pick-caution">Alokasi melebihi stok · Periksa draft</span>':''}`:''}${i.note?`<span class="rack-note">${esc(i.note)}</span>`:''}</span>`;}
function storageView(){const blocks=[...new Set(locs().filter(l=>l.kind==='rack').map(l=>l.block))],count=inventoryFilterCount();return `${sessionBar()}<div class="intro-line"><div><span class="eyebrow">STOK & LOKASI</span><h1>${esc(S.room)}</h1><p class="sub">Tekan-tahan rak untuk memilih. Lorong berada di utara.</p></div><div class="row">${btn('Home','home','','home')}${btn('Muat ulang','refresh','','refresh')}</div></div><div class="bay-toolbar">${btn('Cari / Filter','inventory-search','','search')}${btn('Picking List','pl-home','primary','report')}${btn(S.rackSelection?'Batal pilih':'Pilih rak','rack-select-toggle','small','check')}</div>${count?`<div class="active-filters"><span>${count} filter aktif</span>${btn('Hapus filter','inventory-reset','small')}</div>`:''}${blocks.length?`<nav class="block-tabs block-jumps" aria-label="Navigasi blok">${blocks.map(b=>`<button class="block-tab" data-action="block" data-block="${b}">${b}</button>`).join('')}<button class="block-tab" data-action="block" data-block="FLOOR">Lantai</button></nav>`:''}<p class="notice" id="inventory-count"></p><div class="rack-legend"><span><i class="legend-square"></i>Terisi</span><span><i class="legend-square empty-sq"></i>Kosong</span><span><i class="legend-square hold"></i>Hold</span><span>Depan 1–3 · Belakang 2–4</span></div><div id="rack-content">${rackContent()}</div><div id="selection-container">${selectionBar()}</div>`;}

function rackContent(){
  const locations=locs(),index=new Map(),reservations=Delivery.reservationIndex(S.data);for(const i of modeStock()){if(!index.has(i.locationId))index.set(i.locationId,[]);index.get(i.locationId).push(i);}
  const blocks=[...new Set(locations.filter(l=>l.kind==='rack').map(l=>l.block))];let count=0;
  const sections=blocks.map(block=>{
    const all=locations.filter(l=>l.kind==='rack'&&l.block===block),bays=[...new Set(all.map(l=>l.bay))];
    const markup=bays.map(bay=>{const ls=all.filter(l=>l.bay===bay);if(!ls.some(l=>inventoryLocationMatches(l,index.get(l.id)||[])))return '';count+=ls.filter(l=>inventoryLocationMatches(l,index.get(l.id)||[])).length;
      return `<div class="panel bay"><div class="bay-top"><strong>Bay ${block}${bay}</strong><small>${ls.filter(l=>(index.get(l.id)||[]).length).length}/${ls.length} terisi</small></div><div class="hallway north">LORONG / HALLWAY · UTARA</div><div class="slots">${[1,3,2,4].map(n=>{const loc=ls.find(l=>l.slot===n);if(!loc)return '<div class="missing-slot" aria-label="Slot tidak tersedia">Tidak tersedia</div>';const items=index.get(loc.id)||[],match=inventoryLocationMatches(loc,items),selected=S.rackSelection?S.rackSelected.has(loc.id):S.bulkSelecting?S.emptySelected.has(loc.id):!!items.length&&items.every(i=>S.selected.has(i.id)),pos={1:'Kiri depan',2:'Kiri belakang',3:'Kanan depan',4:'Kanan belakang'}[n];
      return `<button class="slot detailed-slot ${items.length?'filled':''} ${items.some(i=>i.status==='Hold')?'onhold':''} ${loc.functionType!==WMS.FUNCTIONS[0]?'noncomm':''} ${selected?'selected':''} ${match?'':'not-matched'}" data-action="slot" data-id="${esc(loc.id)}" aria-label="Slot ${loc.display}, ${pos}, ${items.length} item" ${S.bulkSelecting&&items.length?'aria-disabled="true"':''} ${S.rackSelection||S.selecting||S.bulkSelecting?`aria-pressed="${selected}"`:''}><span class="slot-id">${loc.display}<span class="rack-mark" data-rack-mark="${selected?'check':!items.length?'plus':''}" aria-hidden="true">${selected?icon('check',12):!items.length?icon('plus',12):''}</span></span>${loc.functionType!==WMS.FUNCTIONS[0]?'<span class="rack-function">Non-komersial</span>':''}${items.length?palletRackMarkup(items,loc,reservations):'<span class="slot-detail">Slot kosong</span>'}</button>`;}).join('')}</div></div>`;}).join('');
    if(!markup)return '';return `<section id="inventory-block-${block}" class="inventory-block"><div class="section-title"><h2>Blok ${block}</h2></div>${S.room==='CSFG C2'&&['N','O','P','Q'].includes(block)?`<div class="info">Bay ${block}1 adalah jalur forklift, tanpa slot.${['P','Q'].includes(block)?' Fast-moving buffer.':''}</div>`:''}<div class="bay-grid">${markup}</div></section>`;
  }).join('');
  const free=locations.filter(l=>!S.bulkSelecting&&l.kind!=='rack').map(loc=>{const items=index.get(loc.id)||[];if(!inventoryLocationMatches(loc,items))return '';count++;return `<section id="inventory-block-${loc.kind==='floor'?'FLOOR':'WIP'}" class="inventory-block"><div class="section-title"><h2>${loc.kind==='floor'?'Lantai':'PROD WIP'}</h2>${btn('+ Tambah palet','edit','small','',`data-id="${esc(loc.id)}" data-add="1"`)}</div>${items.length?`<div class="free-stock-grid">${items.filter(i=>inventoryItemMatches(i,loc)).map(i=>`<div class="panel stock-row">${S.selecting?`<input type="checkbox" class="check" data-select="${esc(i.id)}" aria-label="Pilih ${esc(i.sku)}" ${S.selected.has(i.id)?'checked':''}>`:''}<div class="grow">${stockDetailMarkup(i,loc,reservations)}</div>${btn('Edit','edit','small','',`data-id="${esc(loc.id)}"`)}</div>`).join('')}</div>`:'<div class="empty"><h3>Area ini masih kosong</h3><p>Tambahkan palet untuk mencatat stok.</p></div>'}</section>`;}).join('');
  S.inventoryCount=count;return sections+free||'<div class="empty"><h3>Tidak ada lokasi ditemukan</h3><p>Coba reset filter atau ganti kata kunci.</p></div>';
}
function inventoryCountLabel(){const el=$('#inventory-count');if(el)el.textContent=`${S.inventoryCount||0} lokasi cocok · Detail seluruh item pada rak tetap terlihat; item di luar filter diredupkan.`;}
function jumpToInventory(block){const el=document.getElementById('inventory-block-'+block);if(!el)return toast('Blok tidak ada dalam hasil filter. Reset filter untuk melihat semua rak.');S.block=block;
  // Resolve offscreen card sizes before computing the scroll destination; estimates otherwise drift.
  clearTimeout(S.jumpTimer);const bays=$$('.inventory-block .bay');bays.forEach(b=>b.style.contentVisibility='visible');
  el.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
  S.jumpTimer=setTimeout(()=>bays.forEach(b=>b.style.contentVisibility=''),900);
  $$('.block-tab').forEach(b=>b.classList.toggle('active',b.dataset.block===block));
}
document.addEventListener('change',e=>{const key=e.target.dataset.inventoryFilter;if(key){if(!S.productFilters)S.productFilters={};S.productFilters[key]=e.target.value;updateRacks();inventoryCountLabel();}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="inventory-reset"]')&&!S.busy){S.productFilters={};S.search='';S.filter='all';render();}});

function palletRackMarkup(items,loc,reservations){const rendered=new Set();return items.map(i=>{if(!i.palletId)return stockDetailMarkup(i,loc,reservations);if(rendered.has(i.palletId))return '';rendered.add(i.palletId);const members=items.filter(x=>x.palletId===i.palletId);return '<span class="pallet-combined"><b>P '+esc(Pallets.label(i))+'</b> · '+number(members.reduce((n,x)=>n+x.qty,0))+' '+esc(i.unit)+' · 1 PP</span>'+members.map(x=>stockDetailMarkup(x,loc,reservations)).join('');}).join('');}
