/* Each whole stock item gets one empty rack; confirmation commits every pair together. */
function kpMarkup(kp){return kp?`<time datetime="${esc(kp)}" title="KP ${esc(kp.split('-').reverse().join('.'))}">${esc(WMS.short(kp))}</time>`:'—';}
function moveModal(ids){
 if(!ids.length)return toast('Pilih item yang akan dipindahkan.');
 if(ids.length>100)return toast('Maksimal 100 item per perpindahan. Gunakan Rinci item untuk memilih.');
 if(!Navigation.allowLeave())return;
 if(ids.some(id=>!S.data.stock.some(i=>i.id===id)))return toast('Stok berubah. Pilih ulang barang.');const rows=Pallets.expand(S.data,[...new Set(ids)]);if(rows.length>100)return toast('Gabungan pilihan melebihi 100 komponen. Kurangi pilihan.');
 if(rows.some(i=>!i))return toast('Stok berubah. Muat ulang sebelum memilih ulang.');
 const scroll=window.scrollY||0,room=S.room;
 closeModal();S.moveDraft={merge:false,rows:rows.map(i=>({item:Offline.clone(i),from:i.locationId,destination:''})),expected:{},room,scroll,picking:null,pickerRoom:room,pickerBlock:''};
 for(const r of S.moveDraft.rows)S.moveDraft.expected[r.from]=Offline.fingerprint(S.data,r.from);
 nav('movement');
}
function moveLabel(id){const l=S.data.locations.find(l=>l.id===id);return l?l.room+' / '+l.display:'Belum dipilih';}
function moveItemMarkup(row){const i=row.item;return `<strong>${esc(i.sku)} · ${number(i.qty)} ${esc(i.unit)}</strong><span>KP ${kpMarkup(i.kp)} · Pallet ${esc(Pallets.label(i)||'—')+(i.palletId?' · Asal P '+esc(i.palletNo):'')}${i.spv?' · SPV '+esc(i.spv):''}</span><span>${esc(i.status)} · Dari ${esc(moveLabel(row.from))}</span>`;}
function movementView(){const d=S.moveDraft;if(!d)return '<div class="empty">Tidak ada barang dipilih.</div>';return `<div class="move-workspace"><div class="work-navigation">${btn('Kembali ke Bay','move-exit','','back')}</div><div class="intro-line"><div><span class="eyebrow">PINDAH BARANG</span><h1>Pindahkan barang</h1><p class="sub">${d.merge?'Gabungkan produk dan KP yang sama ke satu pallet fisik. Jumlah per nomor asal tetap tercatat.':'Satu pallet fisik ke satu rak kosong. Pallet gabungan dipindahkan utuh.'}</p></div></div><div class="merge-choice">${btn('Pindah biasa','move-normal',!d.merge?'primary':'')}${btn('Gabungkan ke 1 pallet','move-merge',d.merge?'primary':'')}</div><div id="action-error"></div>${d.picking!==null?movePickerMarkup():moveSummaryMarkup()}</div>`;}
function moveSummaryMarkup(){const d=S.moveDraft,count=d.rows.filter(r=>r.destination).length;return `${d.merge?mergePreview():''}<div class="move-summary">${d.rows.map((r,n)=>`<article class="panel move-pair"><div class="move-item">${moveItemMarkup(r)}</div><div class="move-pair-target"><span>Tujuan</span><strong>${esc(moveLabel(r.destination))}</strong></div><div class="row wrap">${btn(r.destination?'Ganti tujuan':'Pilih tujuan','move-choose',r.destination?'':'primary','warehouse',`data-index="${n}"`)}${btn('Keluarkan dari pilihan','move-remove','small','',`data-index="${n}"`)}</div></article>`).join('')}</div><div class="workflow-save move-save"><strong>${d.merge?(count?'1':'0')+'/1 tujuan gabungan dipilih':count+'/'+d.rows.length+' tujuan dipilih'}</strong>${btn(d.merge?'Konfirmasi gabungan':'Konfirmasi pindah','move-save','primary','move',count===d.rows.length&&count?'':'disabled')}</div>`;}
function movePickerRooms(){return [...new Set(locs(null).filter(l=>l.kind==='rack').map(l=>l.room))];}
function movePickerMarkup(){const d=S.moveDraft,rs=movePickerRooms();if(!rs.includes(d.pickerRoom))d.pickerRoom=rs[0];const ls=locs(null).filter(l=>l.kind==='rack'&&l.room===d.pickerRoom),blocks=[...new Set(ls.map(l=>l.block))];if(!blocks.includes(d.pickerBlock))d.pickerBlock=blocks[0];
 return `<div class="move-picker-head"><div id="move-active" class="panel move-active" aria-live="polite">${moveActiveMarkup()}</div><label class="label">Ruangan tujuan<select class="field" id="move-picker-room">${opts(rs,d.pickerRoom)}</select></label><nav class="block-tabs" aria-label="Blok rak tujuan">${blocks.map(b=>`<button class="block-tab ${b===d.pickerBlock?'active':''}" data-action="move-block" data-block="${esc(b)}">${esc(b)}</button>`).join('')}</nav></div><p class="notice">${d.merge?'Pilih rak kosong atau rak asal yang seluruh isinya ikut digabung. Semua komponen akan ditumpuk di satu pallet.':'Tap rak kosong untuk memasangkan. Satu pallet gabungan dipindahkan utuh ke satu tujuan.'}</p><div class="bay-grid move-grid">${[...new Set(ls.filter(l=>l.block===d.pickerBlock).map(l=>l.bay))].map(bay=>`<section class="panel bay"><div class="bay-top"><strong>Bay ${esc(d.pickerBlock)}${bay}</strong></div><div class="hallway north">LORONG / HALLWAY · UTARA</div><div class="slots">${[1,3,2,4].map(slot=>{const l=ls.find(l=>l.block===d.pickerBlock&&l.bay===bay&&l.slot===slot);if(!l)return '<div class="missing-slot">Tidak tersedia</div>';const state=moveTargetState(l.id);return `<button class="slot move-target ${state.chosen?'selected':''}" data-action="move-target" data-id="${esc(l.id)}" ${state.disabled?'disabled':''} aria-pressed="${state.chosen}" aria-label="Tujuan ${esc(l.display)}: ${esc(state.label)}"><span class="slot-id">${esc(l.display)}</span><span data-move-state>${esc(state.label)}</span></button>`;}).join('')}</div></section>`).join('')}</div><div class="workflow-save move-save"><strong id="move-progress">${d.merge?(d.rows.some(r=>r.destination)?'1':'0')+'/1 tujuan gabungan dipilih':d.rows.filter(r=>r.destination).length+'/'+d.rows.length+' tujuan dipilih'}</strong>${btn('Periksa pasangan','move-review','primary','check')}</div>`;
}
function moveActiveMarkup(){const d=S.moveDraft,r=d.rows[d.picking];if(d.merge)return '<strong>'+ (r?'Pilih satu tujuan untuk seluruh gabungan':'Tujuan gabungan sudah dipilih')+'</strong>'+mergePreview();return r?`<small>Tujuan untuk item ${d.picking+1} dari ${d.rows.length}</small><div class="move-item">${moveItemMarkup(r)}</div>`:'<strong>Semua tujuan sudah dipilih.</strong><p>Tekan Periksa pasangan sebelum menyimpan.</p>';}
function moveTargetState(id){const d=S.moveDraft,chosen=d.rows.some(r=>r.destination===id),occupants=stockAt(id),selected=new Set(d.rows.map(r=>r.item.id)),blocked=occupants.some(i=>!d.merge||!selected.has(i.id));return {chosen,disabled:chosen||blocked||d.picking<0,label:chosen?'Tujuan dipilih':blocked?'Terisi':occupants.length?'Asal pilihan':'Kosong'};}
function chooseMoveTarget(id){const d=S.moveDraft,r=d.rows[d.picking],loc=locs(null).find(l=>l.id===id&&l.kind==='rack');if(!r||!loc||moveTargetState(id).disabled)return;
 for(const row of d.rows)if(d.merge||row===r||r.item.palletId&&row.item.palletId===r.item.palletId)row.destination=id;d.expected[id]=Offline.fingerprint(S.data,id);S.formDirty=true;
 const next=d.rows.findIndex((row,n)=>n>d.picking&&!row.destination);d.picking=next>=0?next:d.rows.findIndex(row=>!row.destination);
 // Preserve grid nodes and scroll while automatically advancing the item prompt.
 $('#move-active').innerHTML=moveActiveMarkup();$('#move-progress').textContent=d.merge?'1/1 tujuan gabungan dipilih':d.rows.filter(row=>row.destination).length+'/'+d.rows.length+' tujuan dipilih';
 $$('.move-target').forEach(el=>{const state=moveTargetState(el.dataset.id);el.disabled=state.disabled;el.classList.toggle('selected',state.chosen);el.setAttribute('aria-pressed',String(state.chosen));el.querySelector('[data-move-state]').textContent=state.label;const loc=locs(null).find(l=>l.id===el.dataset.id);el.setAttribute('aria-label','Tujuan '+loc.display+': '+state.label);});
}
function showMovePage(){render();window.scrollTo({top:0,behavior:'instant'});}
function leaveMove(){if(!Navigation.allowLeave())return;const d=S.moveDraft;S.moveDraft=null;S.room=d?.room||S.room;nav('storage');window.scrollTo({top:d?.scroll||0,behavior:'instant'});}
async function saveMovement(){const d=S.moveDraft;if(!d||S.busy)return;
 try{WMS.assert(d.rows.length&&d.rows.every(r=>r.destination),'Pilih tujuan untuk setiap item.');
  for(const id of new Set(d.rows.flatMap(r=>[r.from,r.destination])))WMS.assert(d.expected[id]===Offline.fingerprint(S.data,id),'Data asal/tujuan berubah. Kembali ke Bay dan susun ulang perpindahan.');
  if(await mutate(d.merge?{action:'mergePallet',ids:d.rows.map(r=>r.item.id),destination:d.rows[0].destination}:{action:'moveBatch',rows:d.rows.map(r=>({itemId:r.item.id,from:r.from,destination:r.destination}))})){leaveMove();toast('Semua barang dipindahkan'+(gas?' di HP · Menunggu SYNC.':'.'));}
 }catch(e){storageError(e);}
}
document.addEventListener('change',e=>{if(e.target.id==='move-picker-room'&&!S.busy){S.moveDraft.pickerRoom=e.target.value;S.moveDraft.pickerBlock='';showMovePage();}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||S.busy)return;const d=S.moveDraft;switch(b.dataset.action){
 case 'move-normal':setMergeMode(false);break;
 case 'move-merge':setMergeMode(true);break;
 case 'move-choose':d.picking=Number(b.dataset.index);{const l=S.data.locations.find(l=>l.id===(d.rows[d.picking].destination||d.rows[d.picking].from));d.pickerRoom=l?.kind==='rack'?l.room:movePickerRooms()[0];d.pickerBlock=l?.block||'';}showMovePage();break;
 case 'move-remove':{const removed=d.rows[Number(b.dataset.index)];d.rows=d.rows.filter(r=>r!==removed&&(!removed.item.palletId||r.item.palletId!==removed.item.palletId));}S.formDirty=true;if(!d.rows.length){Navigation.saved();leaveMove();}else showMovePage();break;
 case 'move-block':d.pickerBlock=b.dataset.block;showMovePage();break;
 case 'move-target':chooseMoveTarget(b.dataset.id);break;
 case 'move-review':d.picking=null;showMovePage();break;
 case 'move-exit':leaveMove();break;
 case 'move-save':await saveMovement();break;
}});

function mergePreview(){const rows=S.moveDraft.rows.map(r=>r.item),numbers=[...new Set(rows.flatMap(i=>Pallets.label(i).split(',')))];return '<div class="panel workflow-panel"><h2>P '+esc(numbers.join(','))+'</h2><p>'+number(rows.reduce((n,i)=>n+i.qty,0))+' '+esc(rows[0]?.unit||'CTN')+' · 1 pallet fisik</p><p class="notice">Rincian asal tetap disimpan. Produk, KP, satuan, dan status harus sama; kode SPV/notes tetap mengikuti masing-masing asal. Penggabungan tidak membuat transaksi IN/OUT.</p></div>';}
function setMergeMode(value){const d=S.moveDraft;try{if(value){const rows=d.rows.map(r=>r.item),first=rows[0];WMS.assert(Pallets.count(rows)>=2,'Pilih minimal dua pallet fisik.');WMS.assert(rows.every(i=>['sku','kp','unit','status'].every(k=>i[k]===first[k])),'Gabungkan hanya produk, KP, satuan, dan status yang sama.');WMS.assert(rows.every(i=>i.palletNo),'Isi nomor pallet asal terlebih dahulu.');}d.merge=value;d.picking=null;d.rows.forEach(r=>r.destination='');S.formDirty=true;showMovePage();}catch(e){toast(errorText(e));}}
