// Selection only changes decoration: never replace Bay nodes or disturb scroll/focus.
function updateSelectionUI(){
 const index=new Map();for(const i of modeStock()){if(!index.has(i.locationId))index.set(i.locationId,[]);index.get(i.locationId).push(i);}
 $$('#rack-content [data-action="slot"]').forEach(el=>{
  const id=el.dataset.id,items=index.get(id)||[];
  const chosen=S.rackSelection?!!S.rackSelected?.has(id):S.bulkSelecting?!!S.emptySelected?.has(id):!!items.length&&items.every(i=>S.selected.has(i.id));
  el.classList.toggle('selected',chosen);
  if(S.rackSelection||S.selecting||S.bulkSelecting)el.setAttribute('aria-pressed',String(chosen));else el.removeAttribute('aria-pressed');
  const mark=el.querySelector('[data-rack-mark]'),state=chosen?'check':items.length?'':'plus';
  if(mark&&mark.dataset.rackMark!==state){mark.dataset.rackMark=state;mark.innerHTML=state?icon(state,12):'';}
 });
 const bar=$('#selection-container');if(bar)bar.innerHTML=selectionBar();
 const toggle=$('[data-action="rack-select-toggle"]');if(toggle){toggle.textContent=S.rackSelection?'Batal pilih':'Pilih rak';toggle.setAttribute('aria-label',toggle.textContent);}
}
function inventoryFilterCount(){return Object.values(S.productFilters||{}).filter(Boolean).length+(S.search.trim()?1:0)+(S.filter!=='all'?1:0);}
function openInventorySearch(){const f=S.productFilters||{};openModal('Cari / Filter','Terapkan untuk menyaring rak. Navigasi alfabet tetap tersedia.',`<label class="label">Cari stok<input id="inv-query" class="field" value="${esc(S.search)}" placeholder="Produk, lokasi, KP, atau pallet"></label><div class="two-col"><label class="label">Isi rak<select class="field" id="inv-occupancy">${[['all','Semua rak'],['filled','Terisi'],['empty','Kosong'],['noncomm','Non-komersial']].map(([v,l])=>`<option value="${v}" ${v===S.filter?'selected':''}>${l}</option>`).join('')}</select></label><label class="label">Status<select class="field" data-inv-filter="status" aria-label="Filter status"><option value="">Semua status</option>${opts(WMS.STATUS,f.status)}</select></label><label class="label">Produk<select class="field" data-inv-filter="sku" aria-label="Filter produk"><option value="">Semua produk</option>${opts(S.data.skus.filter(s=>s.group===S.mode).map(s=>s.code),f.sku)}</select></label><label class="label">KP<input type="date" class="field" data-inv-filter="kp" aria-label="Filter KP" value="${esc(f.kp||'')}"></label><label class="label">Jumlah tepat<input type="number" min="1" step="1" inputmode="numeric" class="field" data-inv-filter="qty" aria-label="Filter jumlah" value="${esc(f.qty||'')}" placeholder="Semua jumlah"></label>${S.mode==='CSFG'?`<label class="label">Kode SPV<select class="field" data-inv-filter="spv" aria-label="Filter SPV"><option value="">Semua SPV</option>${opts(['JT','HW','AK','-'],f.spv)}</select></label>`:''}</div>`,`${btn('Reset','filter-clear')}${btn('Terapkan','filter-apply','primary','check')}`);}
function cancelRackSelection(){S.rackSelection=false;S.rackSelected=new Set();S.selected.clear();S.selecting=false;S.bulkSelecting=false;updateSelectionUI();const toggle=$('[data-action="rack-select-toggle"]');if(toggle){toggle.textContent='Pilih rak';toggle.setAttribute('aria-label','Pilih rak');}}
function toggleRack(id){const loc=locs().find(l=>l.id===id&&l.kind==='rack');if(!loc)return;S.rackSelection=true;if(!S.rackSelected)S.rackSelected=new Set();if(S.rackSelected.has(id)){S.rackSelected.delete(id);stockAt(id).forEach(i=>S.selected.delete(i.id));}else {if(S.rackSelected.size>=100)return toast('Maksimal 100 rak dipilih.');S.rackSelected.add(id);stockAt(id).forEach(i=>S.selected.add(i.id));}S.selecting=true;updateSelectionUI();const toggle=$('[data-action="rack-select-toggle"]');if(toggle){toggle.textContent='Batal pilih';toggle.setAttribute('aria-label','Batal pilih');}}
function rackActionBar(){const ids=[...(S.rackSelected||[])],empty=ids.filter(id=>!stockAt(id).length).length;return `<div class="rack-action-bar"><div class="row between"><strong>${ids.length} rak · ${empty} kosong · ${ids.length-empty} terisi</strong>${btn('Batal','rack-cancel','small','close')}</div><div class="rack-actions">${btn('Isi ('+empty+')','rack-fill','small','plus',empty?'':'disabled')}${btn('Move ('+S.selected.size+')','rack-move','small','move',S.selected.size?'':'disabled')}${btn('Barang keluar','rack-out','small','truck',S.selected.size?'':'disabled')}${S.selected.size?btn('Rinci item','select-details','small'):''}</div></div>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||S.busy)return;switch(b.dataset.action){case 'inventory-search':openInventorySearch();break;case 'filter-apply':S.search=$('#inv-query').value;S.filter=$('#inv-occupancy').value;S.productFilters={};$$('[data-inv-filter]').forEach(el=>S.productFilters[el.dataset.invFilter]=el.value);closeModal();render();break;case 'filter-clear':S.search='';S.filter='all';S.productFilters={};closeModal();render();break;case 'rack-select-toggle':if(S.rackSelection)cancelRackSelection();else {S.rackSelection=true;S.rackSelected=new Set();S.selected.clear();S.selecting=true;updateSelectionUI();}break;case 'rack-cancel':cancelRackSelection();break;case 'rack-fill':S.emptySelected=new Set([...(S.rackSelected||[])].filter(id=>!stockAt(id).length));openBulkInput();break;case 'rack-move':moveModal([...S.selected]);break;case 'rack-out':if(S.selected.size>100)return toast('Maksimal 100 item per picking list. Gunakan Rinci item untuk memilih.');openDeliveryDraft(null,[...S.selected]);break;}});
// Cancel a pending hold as soon as scrolling/dragging begins. A completed hold consumes its click.
(()=>{let pending=null,suppressed=null;function cancel(){if(pending)clearTimeout(pending.timer);pending=null;}
 document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-action="slot"]');if(!b||S.busy||e.button!==0)return;cancel();const id=b.dataset.id;pending={x:e.clientX,y:e.clientY,id,pointer:e.pointerId,timer:setTimeout(()=>{pending=null;suppressed={id,until:Date.now()+1200};toggleRack(id);},500)};});
 document.addEventListener('pointermove',e=>{if(pending&&(Math.abs(e.clientX-pending.x)>10||Math.abs(e.clientY-pending.y)>10))cancel();},{passive:true});
 document.addEventListener('pointerup',cancel);document.addEventListener('pointercancel',cancel);document.addEventListener('scroll',cancel,true);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action="slot"]');if(b&&suppressed&&suppressed.id===b.dataset.id&&Date.now()<suppressed.until){suppressed=null;e.preventDefault();e.stopImmediatePropagation();}},true);
 document.addEventListener('contextmenu',e=>{const b=e.target.closest('[data-action="slot"]');if(b){e.preventDefault();if(!S.rackSelection&&!pending)toggleRack(b.dataset.id);}});
 document.addEventListener('keydown',e=>{const b=e.target.closest('[data-action="slot"]');if(b&&e.key===' '&&e.shiftKey){e.preventDefault();toggleRack(b.dataset.id);}});
})();
