const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
function env(){
  const sheets=new Map(),props=new Map();let lockCount=0,releaseCount=0,fail=false,batchCount=0,batchFail=false,dropReply=false;
  class Range {constructor(s,r,c,n,w){Object.assign(this,{s,r,c,n,w});}getValues(){return Array.from({length:this.n},(_,ri)=>Array.from({length:this.w},(_,ci)=>this.s.rows[this.r-1+ri]?.[this.c-1+ci]??''));}setValues(rows){if(fail&&this.s.name==='Stock_Detail'){fail=false;throw Error('Injected write error');}for(let r=0;r<this.n;r++){this.s.rows[this.r-1+r]??=[];for(let c=0;c<this.w;c++){const v=rows[r][c];this.s.rows[this.r-1+r][this.c-1+c]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v;}}return this;}clearContent(){for(let r=0;r<this.n;r++)for(let c=0;c<this.w;c++)if(this.s.rows[this.r-1+r])this.s.rows[this.r-1+r][this.c-1+c]='';return this;}setNumberFormat(){return this;}setBackground(){return this;}setFontColor(){return this;}setFontWeight(){return this;}}
  class Sheet {constructor(name){this.name=name;this.id=sheets.size+1;this.rows=[];this.max=1000;}getSheetId(){return this.id;}getLastRow(){let n=this.rows.length;while(n>0&&!(this.rows[n-1]||[]).some(v=>v!==''))n--;return n;}getRange(r,c,n,w){return new Range(this,r,c,n,w);}getMaxRows(){return this.max;}insertRowsAfter(n,count){this.max+=count;}setFrozenRows(){}appendRow(row){this.getRange(this.getLastRow()+1,1,1,row.length).setValues([row]);}}
  const db={getId:()=> 'test-db',getSheetByName:n=>sheets.get(n),insertSheet:n=>{const s=new Sheet(n);sheets.set(n,s);return s;}};
  const context=vm.createContext({console,Date,Set,Map,JSON,SpreadsheetApp:{getActiveSpreadsheet:()=>db,openById:()=>db,flush:()=>{}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v)})},LockService:{getScriptLock:()=>({waitLock:()=>lockCount++,releaseLock:()=>releaseCount++})},Utilities:{getUuid:()=>require('crypto').randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(algorithm,value)=>[...require('crypto').createHash('sha256').update(value).digest()]},Sheets:{Spreadsheets:{batchUpdate:({requests})=>{batchCount++;if(batchFail){batchFail=false;throw Error('API failure before commit');}const backup=[...sheets.values()].map(s=>[s,JSON.parse(JSON.stringify(s.rows)),s.max]);try{for(const req of requests){const spec=req.appendDimension||req.updateCells,range=spec.range||spec;const sheet=[...sheets.values()].find(s=>s.id===range.sheetId);if(req.appendDimension){sheet.max+=spec.length;continue;}for(let r=range.startRowIndex;r<range.endRowIndex;r++){sheet.rows[r]??=[];for(let c=range.startColumnIndex;c<range.endColumnIndex;c++){const v=spec.rows[r-range.startRowIndex]?.values[c-range.startColumnIndex]?.userEnteredValue;sheet.rows[r][c]=v?(v.numberValue??v.stringValue):'';}}}}catch(err){for(const [s,rows,max] of backup){s.rows=rows;s.max=max;}throw err;}if(dropReply){dropReply=false;throw Error('Network response lost after commit');}return {};}}}});
  vm.runInContext(fs.readFileSync('Code.gs','utf8')+'\n'+fs.readFileSync('Setup.gs','utf8')+'\nthis.Off=Offline;',context);
  return {context,sheets,props,counts:()=>[lockCount,releaseCount],fail:()=>fail=true,failBatch:()=>batchFail=true,loseReply:()=>dropReply=true,batches:()=>batchCount};
}
const input={name:'QA SK',date:'2026-09-07',shift:'S1',mode:'CSFG'};

test('approved pallet104 repair preserves30, splits identities and can be rerun safely',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const id='e8113d62-4f51-46f3-bb65-c70b1a9a5afe',stock=e.sheets.get('Stock_Detail').rows[1];stock[0]=id;stock[2]='PCN';stock[3]='2026-09-28';stock[4]='2026-09-28';stock[5]=30;stock[8]='Hold';stock[12]='104';const fields=vm.runInContext('StockExport.fields',e.context),base=e.context.getStockExport(ss.id).rows[0],ledger=e.sheets.get('Transaction_Log');ledger.rows=[Array.from(fields),...['CCN','PCN'].map((sku,n)=>fields.map(k=>({...base,id:'IN-test-'+n,itemId:id,sku,kp:'2026-09-28',palletNo:'104',status:'Hold',qty:n?14:16})[k]??''))];e.context.repairPallet104_();let data=e.context.getBootstrap(ss.id);assert.equal(data.stock.length,2);assert.equal(data.stock.reduce((n,i)=>n+i.qty,0),30);assert.deepEqual(Array.from(data.stock,i=>i.qty),[16,14]);assert.equal(new Set(data.stock.map(i=>i.id)).size,2);const before=ledger.getLastRow();e.context.repairPallet104_();assert.equal(ledger.getLastRow(),before);assert.equal(e.context.getStockExport(ss.id).rows.filter(r=>r.type==='IN').reduce((n,r)=>n+r.qty,0),30);});

test('correction commits stock and before/after audit atomically and a lost reply does not duplicate',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const initial=e.context.getBootstrap(ss.id),O=e.context.Off,request={version:initial.version,action:'correctItem',itemId:initial.stock[0].id,before:{...initial.stock[0]},item:{...initial.stock[0],qty:25},reason:'Salah input penerimaan'};let cache=O.freeze(O.enqueue(O.initial(initial),request,ss,require('crypto').randomUUID,'2026-09-30T01:00:00Z'),require('crypto').randomUUID);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/failure/);assert.equal(e.context.getBootstrap(ss.id).stock[0].qty,30);assert.equal(e.context.getStockExport(ss.id).rows.filter(r=>r.type==='KOREKSI').length,0);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/lost/);const reply=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(reply.replayed,true);assert.equal(reply.data.stock[0].qty,25);const rows=e.context.getStockExport(ss.id).rows;assert.equal(rows.filter(r=>r.type==='IN')[0].qty,30);const corrections=rows.filter(r=>r.type==='KOREKSI');assert.equal(corrections.length,1);assert.equal(corrections[0].qty,-5);assert.equal(JSON.parse(corrections[0].beforeJson).qty,30);assert(corrections[0].sequence>0);});

test('physical merge sync is atomic and idempotent, group columns survive reload and history remains original',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;const receive=bulkBatch(e,ss);e.context.syncOfflineBatch(ss.id,receive.inflight);const initial=e.context.getBootstrap(ss.id),O=e.context.Off;let state=O.enqueue(O.initial(initial),{version:initial.version,action:'mergePallet',ids:initial.stock.map(i=>i.id),destination:'CSFG C1:B1-1'},ss,require('crypto').randomUUID,'2026-09-23T01:00:00Z');state=O.freeze(state,require('crypto').randomUUID);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,state.inflight),/API failure/);assert(e.context.getBootstrap(ss.id).stock.every(i=>!i.palletId));e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,state.inflight),/lost/);const ack=e.context.syncOfflineBatch(ss.id,state.inflight);assert.equal(ack.replayed,true);const d=e.context.getBootstrap(ss.id);assert.equal(new Set(d.stock.map(i=>i.palletId)).size,1);assert(d.stock.every(i=>i.palletLabel==='31,125'));assert.equal(e.context.getStockExport(ss.id).rows.length,2);assert.equal(e.sheets.get('Stock_Detail').rows[0][13],'Physical_Pallet_ID');assert.equal(e.sheets.get('Delivery_Lines').rows[0][15],'palletId');});
test('stock group migration rejects occupied custom columns without overwriting their values',()=>{const e=env();e.context.setupDatabase_();const sheet=e.sheets.get('Stock_Detail');sheet.rows[0][13]='Custom business field';assert.throws(()=>e.context.startSession(input),/Kolom 14/);assert.equal(sheet.rows[0][13],'Custom business field');});

test('export ledger is atomic with stock and receipt, survives lost response and reload',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/lost/);e.context.syncOfflineBatch(ss.id,cache.inflight);const result=e.context.getStockExport(ss.id);assert.equal(result.rows.length,1);assert.equal(result.rows[0].type,'IN');assert.equal(result.rows[0].qty,30);assert.equal(result.rows[0].room,'CSFG C1');assert.equal(result.rows[0].palletNo,'7');assert.equal(result.rows[0].date,input.date);assert.equal(e.sheets.get('Transaction_Log').getLastRow(),2);});
test('failed batch adds neither receipt history nor stock, and successful retry records once',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=bulkBatch(e,ss);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/API failure/);assert.equal(e.context.getStockExport(ss.id).rows.length,0);assert.equal(e.context.getBootstrap(ss.id).stock.length,0);e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(e.context.getStockExport(ss.id).rows.length,2);});
test('export retains original IN after full outbound and old issued DN fallback never duplicates',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const cache=deliveryBatch(e,ss,30);e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(e.context.getBootstrap(ss.id).stock.length,0);let records=e.context.getStockExport(ss.id).rows;assert.equal(records.length,2);assert.equal(records.filter(r=>r.type==='IN')[0].qty,30);const id=records.filter(r=>r.type==='OUT')[0].id;assert.equal(e.context.getStockExport(ss.id).rows.length,2);const ledger=e.sheets.get('Transaction_Log');ledger.rows=ledger.rows.filter((r,n)=>!n||r[1]!=='OUT');records=e.context.getStockExport(ss.id).rows;assert.equal(records.length,2);assert.equal(records.find(r=>r.type==='OUT').id,id);});
test('export authorization isolates categories and rejects unknown session; no fabricated old IN',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const other=e.context.startSession({...input,mode:'CHILLER'}).session;assert.equal(e.context.getStockExport(other.id).rows.length,0);assert.throws(()=>e.context.getStockExport('unknown-session-0000000000'));e.sheets.get('Transaction_Log').rows.length=1;assert.equal(e.context.getBootstrap(ss.id).stock.length,1);assert.equal(e.context.getStockExport(ss.id).rows.length,0);});
test('direct legacy endpoint commits receipt and stock together; failed quantity increase does not add IN',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;const d=save(e,ss),r={version:d.version,action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[{...d.stock[0],qty:35}]};e.failBatch();assert.throws(()=>e.context.mutateStock(ss.id,r),/Simpan gagal/);assert.equal(e.context.getStockExport(ss.id).rows.length,1);const fresh=e.context.getBootstrap(ss.id);assert.equal(fresh.stock[0].qty,30);e.context.mutateStock(ss.id,{...r,version:fresh.version});const rows=e.context.getStockExport(ss.id).rows;assert.equal(rows.length,2);assert.equal(rows.reduce((n,r)=>n+r.qty,0),35);});

function legacyC2(e){const sheet=e.sheets.get('Master_Lokasi');sheet.rows=sheet.rows.filter((r,n)=>!n||!/^CHILLER C2:(AA|BB)/.test(r[0]));}
test('existing database gains only 26 C2 racks once and preserves every existing row, stock and draft',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const draft=deliveryBatch(e,ss,12,false);e.context.syncOfflineBatch(ss.id,draft.inflight);legacyC2(e);const sheet=e.sheets.get('Master_Lokasi');sheet.rows.find(r=>r[0]==='CHILLER C2:A1-1')[9]='Bingkisan / Non-Komersial';const old=JSON.stringify(sheet.rows),stock=JSON.stringify(e.sheets.get('Stock_Detail').rows),docs=JSON.stringify(e.sheets.get('Delivery_Lines').rows),batches=e.batches(),oldCount=sheet.rows.length;const data=e.context.getBootstrap(ss.id);assert.equal(data.locations.length,510);assert.equal(sheet.rows.length,oldCount+26);assert.equal(JSON.stringify(sheet.rows.slice(0,oldCount)),old);assert.equal(JSON.stringify(e.sheets.get('Stock_Detail').rows),stock);assert.equal(JSON.stringify(e.sheets.get('Delivery_Lines').rows),docs);assert.equal(e.batches(),batches+1);e.context.getBootstrap(ss.id);assert.equal(e.batches(),batches+1);assert.equal(new Set(sheet.rows.slice(1).map(r=>r[0])).size,sheet.rows.length-1);});
test('failed C2 migration leaves old master intact and retries; lost response cannot duplicate racks',()=>{for(const loss of [false,true]){const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;legacyC2(e);const old=JSON.stringify(e.sheets.get('Master_Lokasi').rows);if(loss)e.loseReply();else e.failBatch();assert.throws(()=>e.context.getBootstrap(ss.id),loss?/lost/:/API failure/);if(!loss)assert.equal(JSON.stringify(e.sheets.get('Master_Lokasi').rows),old);e.context.getBootstrap(ss.id);const rows=e.sheets.get('Master_Lokasi').rows.filter(r=>/^CHILLER C2:(AA|BB)/.test(r[0]));assert.equal(rows.length,26);assert.equal(new Set(rows.map(r=>r[0])).size,26);}});
test('old offline Chiller operation syncs across additive migration without losing new racks or old stock',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession({...input,mode:'CHILLER'}).session;const data=e.context.getBootstrap(ss.id);data.locations=data.locations.filter(l=>!/^CHILLER C2:(AA|BB)/.test(l.id));const O=e.context.Off,cache=O.freeze(O.enqueue(O.initial(data),{version:data.version,action:'saveSlot',locationId:'CHILLER C2:A1-1',functionType:'Reguler',items:[{...row,sku:'BG',qty:48}]},ss,require('crypto').randomUUID,'2026-09-14T01:00:00.000Z'),require('crypto').randomUUID);legacyC2(e);const reply=e.context.syncOfflineBatch(ss.id,cache.inflight);assert(!reply.conflict);assert.equal(reply.data.locations.filter(l=>l.room==='CHILLER C2'&&l.kind==='rack').length,486);assert.equal(reply.data.stock[0].qty,48);assert.equal(O.acknowledge(cache,reply).queue.length,0);});

test('concurrent drafts cannot overreserve even though saving a draft leaves the stock fingerprint unchanged',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const a=deliveryBatch(e,ss,20,false),b=deliveryBatch(e,ss,20,false);e.context.syncOfflineBatch(ss.id,a.inflight);assert.throws(()=>e.context.syncOfflineBatch(ss.id,b.inflight),/Sisa tersedia.*10 CTN/);const d=e.context.getBootstrap(ss.id);assert.equal(d.stock[0].qty,30);assert.equal(d.deliveryNotes.length,1);assert.equal(e.batches(),2);assert.equal(b.queue.length,1);});

test('two independently prepared drafts within available balance sync and survive receipt replay',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const a=deliveryBatch(e,ss,12,false),b=deliveryBatch(e,ss,10,false);e.context.syncOfflineBatch(ss.id,a.inflight);e.context.syncOfflineBatch(ss.id,b.inflight);e.context.syncOfflineBatch(ss.id,b.inflight);const d=e.context.getBootstrap(ss.id);assert.equal(d.stock[0].qty,30);assert.equal(d.deliveryNotes.length,2);assert.equal(d.deliveryNotes.reduce((n,d)=>n+d.lines[0].qty,0),22);assert.equal(e.batches(),3);});
const row={sku:'CCN',kp:'2026-09-04',qty:30,unit:'CTN',spv:'-',status:'Release',note:'=literal note'};
function save(e,ss,version=0){return e.context.mutateStock(ss.id,{version,action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[row]});}
test('GAS editor setup helper initializes database idempotently and leaves stock empty',()=>{const e=env();assert.match(e.context.setupDatabase(),/Database siap/);e.context.setupDatabase();assert.equal(e.sheets.size,4);assert.equal(e.sheets.get('Master_Lokasi').getLastRow(),1545);assert.equal(e.sheets.get('Stock_Detail').getLastRow(),1);assert.deepEqual(e.counts(),[2,2]);});
test('GAS session, CRUD, reload and report serialize and preserve literal notes',()=>{const e=env();e.context.setupDatabase_();const result=e.context.startSession(input),ss=result.session;assert.equal(result.data.locations.length,510);const saved=save(e,ss);assert.equal(saved.stock[0].spv,'-');assert.equal(saved.stock[0].note,'=literal note');const reloaded=e.context.getBootstrap(ss.id);assert.equal(reloaded.stock[0].qty,30);assert.equal(reloaded.stock[0].note,'=literal note');assert.match(e.context.generateWaText(ss.id,'CSFG C1'),/CCN 04.09 = 30 - =literal note/);assert.deepEqual(e.counts(),[5,5]);});
test('GAS stale session and unknown session rejected; locks released on errors',()=>{const e=env();e.context.setupDatabase_();assert.throws(()=>e.context.getBootstrap('unknown-session-0000000000'));const ss=e.context.startSession(input).session;const sessionSheet=e.sheets.get('User_Session');sessionSheet.rows[1][6]='2000-01-01T00:00:00Z';assert.throws(()=>e.context.getBootstrap(ss.id),/kedaluwarsa/);assert.equal(e.counts()[0],e.counts()[1]);});
test('GAS stale revision does not change persisted stock',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);assert.throws(()=>save(e,ss,0),/CONFLICT/);assert.equal(e.context.getBootstrap(ss.id).stock.length,1);assert.equal(e.props.get('WMS_REV'),'1');});
test('GAS atomic failure preserves stock and ledger and invalidates stale revision',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;const saved=save(e,ss);e.failBatch();assert.throws(()=>e.context.mutateStock(ss.id,{version:1,action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[{...saved.stock[0],qty:31}]}),/Simpan gagal/);assert.equal(e.context.getBootstrap(ss.id).stock.length,1);assert.equal(e.props.get('WMS_REV'),'2');assert.equal(e.counts()[0],e.counts()[1]);});
test('GAS upgrades legacy 12-column Stock_Detail without changing stock or notes',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const sheet=e.sheets.get('Stock_Detail');sheet.rows.forEach(r=>r.length=12);const before=JSON.stringify(sheet.rows[1]);e.context.setupDatabase_();assert.equal(sheet.rows[0][12],'No_Pallet');assert.equal(JSON.stringify(sheet.rows[1]),before);const d=e.context.getBootstrap(ss.id);assert.equal(d.stock[0].palletNo,'');assert.equal(d.stock[0].note,'=literal note');});
test('GAS reads back pallet as text and emits report after edit',()=>{const e=env();e.context.setupDatabase_();const {session:ss,data}=e.context.startSession(input);e.context.mutateStock(ss.id,{version:data.version,action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[{...row,palletNo:'0031'}]});assert.equal(e.context.getBootstrap(ss.id).stock[0].palletNo,'31');assert.equal(e.sheets.get('Stock_Detail').rows[1][12],'31');assert.match(e.context.generateWaText(ss.id,'CSFG C1'),/\(P:31\)/);});
test('GAS migration does not overwrite a custom thirteenth column',()=>{const e=env();e.context.setupDatabase_();e.sheets.get('Stock_Detail').rows[0][12]='Custom';assert.throws(()=>e.context.startSession(input),/Kolom ke-13/);assert.equal(e.sheets.get('Stock_Detail').rows[0][12],'Custom');});
function offlineBatch(e,ss,actor=ss){const O=e.context.Off;let cache=O.initial(e.context.getBootstrap(ss.id));cache=O.enqueue(cache,{version:cache.data.version,action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[{...row,palletNo:'0007'}]},actor,require('crypto').randomUUID,'2026-09-10T01:00:00.000Z');cache=O.enqueue(cache,{version:cache.data.version,action:'move',ids:[cache.data.stock[0].id],destination:'WIP-CSFG'},actor,require('crypto').randomUUID,'2026-09-10T01:01:00.000Z');return O.freeze(cache,require('crypto').randomUUID);}
test('offline batch commits two operations and receipt in one atomic API request',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss),result=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(result.ackIds.length,2);assert.equal(result.data.stock.length,1);assert.equal(result.data.stock[0].locationId,'WIP-CSFG');assert.equal(result.data.stock[0].palletNo,'7');assert.equal(e.batches(),1);assert.equal(e.sheets.get('Sync_Log').getLastRow(),2);});
test('lost response retries same batch without duplicate data or duplicate receipt',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/lost/);assert.equal(e.context.getBootstrap(ss.id).stock.length,1);const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.replayed,true);assert.equal(e.batches(),1);assert.equal(e.sheets.get('Sync_Log').getLastRow(),2);assert.equal(e.context.Off.acknowledge(cache,r).queue.length,0);});
test('atomic API failure preserves stock and leaves no receipt; retry can succeed',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/API failure/);assert.equal(e.context.getBootstrap(ss.id).stock.length,0);assert.equal(e.sheets.get('Sync_Log').getLastRow(),1);assert.equal(e.context.syncOfflineBatch(ss.id,cache.inflight).data.stock.length,1);});
test('same-location conflict does not partially apply batch or acknowledge it',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss);save(e,ss);const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.conflict,true);assert.equal(e.context.getBootstrap(ss.id).stock[0].locationId,'CSFG C1:A1-1');assert.equal(e.batches(),1);assert.equal(e.sheets.get('Sync_Log').getLastRow(),1);});
test('unrelated room edit is preserved when offline batch syncs',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss);e.context.mutateStock(ss.id,{version:0,action:'saveSlot',locationId:'CSFG C2:A3-1',functionType:'Reguler',items:[row]});const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.data.stock.length,2);assert(r.data.stock.some(i=>i.locationId==='CSFG C2:A3-1'));});
test('receipt rejects a changed payload under an already committed batch ID',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=offlineBatch(e,ss);e.context.syncOfflineBatch(ss.id,cache.inflight);cache.inflight.operations[0].request.items[0].qty=99;assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/isi yang berbeda/);assert.equal(e.context.getBootstrap(ss.id).stock[0].qty,30);});
test('offline actor session is preserved in history but never authorized as an active token',()=>{const e=env();e.context.setupDatabase_();const live=e.context.startSession(input).session,offline={...live,id:require('crypto').randomUUID(),name:'Offline operator'},cache=offlineBatch(e,live,offline);const r=e.context.syncOfflineBatch(live.id,cache.inflight);assert.equal(r.data.stock[0].sessionId,offline.id);assert.throws(()=>e.context.getBootstrap(offline.id),/kedaluwarsa/);});

function deliveryBatch(e,ss,qty=7,issue=true){const O=e.context.Off;let cache=O.initial(e.context.getBootstrap(ss.id));const id=require('crypto').randomUUID();const operations=[{action:'saveDelivery',documentId:id,documentRevision:0,date:input.date,destination:'Packing',note:'=literal destination note',lines:[{itemId:cache.data.stock[0].id,qty}]}];if(issue)operations.push({action:'issueDelivery',sjNumber:'0000123456',documentId:id,documentRevision:1});for(const request of operations)cache=O.enqueue(cache,{version:cache.data.version,...request},ss,require('crypto').randomUUID,'2026-09-11T01:00:00.000Z');return O.freeze(cache,require('crypto').randomUUID);}

function pairedBatch(e,ss){const O=e.context.Off,data=e.context.getBootstrap(ss.id),request={version:data.version,action:'moveBatch',rows:data.stock.map((i,n)=>({itemId:i.id,from:i.locationId,destination:n?'CSFG C1:B2-3':'CSFG C1:B2-1'}))};return O.freeze(O.enqueue(O.initial(data),request,ss,require('crypto').randomUUID,'2026-09-14T01:00:00.000Z'),require('crypto').randomUUID);}
test('paired movement sync commits draft locations and stock together, retry after lost response moves only once',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const pl=deliveryBatch(e,ss,12,false);e.context.syncOfflineBatch(ss.id,pl.inflight);const batch=pairedBatch(e,ss);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,batch.inflight),/lost/);const reply=e.context.syncOfflineBatch(ss.id,batch.inflight);assert.equal(reply.replayed,true);assert.equal(reply.data.stock[0].locationId,'CSFG C1:B2-1');assert.equal(reply.data.deliveryNotes[0].lines[0].location,'B2-1');assert.equal(reply.data.deliveryNotes[0].revision,2);assert.equal(e.context.Off.acknowledge(batch,reply).queue.length,0);});
test('paired movement target conflict leaves all origins and draft snapshots unchanged',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;let data=save(e,ss);data=e.context.mutateStock(ss.id,{version:data.version,action:'saveSlot',locationId:'CSFG C1:A1-3',functionType:'Reguler',items:[row]});const batch=pairedBatch(e,ss);e.context.mutateStock(ss.id,{version:data.version,action:'saveSlot',locationId:'CSFG C1:B2-3',functionType:'Reguler',items:[row]});const reply=e.context.syncOfflineBatch(ss.id,batch.inflight);assert.equal(reply.conflict,true);const fresh=e.context.getBootstrap(ss.id);assert.equal(fresh.stock[0].locationId,'CSFG C1:A1-1');assert.equal(fresh.stock[1].locationId,'CSFG C1:A1-3');assert.equal(batch.queue.length,1);assert.equal(e.batches(),3);});
test('concurrent picking revision conflicts with queued movement instead of overwriting changed allocations',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const pl=deliveryBatch(e,ss,12,false);e.context.syncOfflineBatch(ss.id,pl.inflight);const batch=pairedBatch(e,ss),data=e.context.getBootstrap(ss.id),doc=data.deliveryNotes[0],O=e.context.Off;const changed=O.freeze(O.enqueue(O.initial(data),{action:'saveDelivery',version:data.version,documentId:doc.id,documentRevision:doc.revision,date:input.date,destination:'Truk lain',lines:[{itemId:data.stock[0].id,qty:10}]},ss,require('crypto').randomUUID,'2026-09-14T01:00:00.000Z'),require('crypto').randomUUID);e.context.syncOfflineBatch(ss.id,changed.inflight);assert.equal(e.context.syncOfflineBatch(ss.id,batch.inflight).conflict,true);assert.equal(e.context.getBootstrap(ss.id).deliveryNotes[0].lines[0].qty,10);assert.equal(e.context.getBootstrap(ss.id).stock[0].locationId,'CSFG C1:A1-1');});
test('paired movement API failure preserves stock, drafts and pending queue for retry',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const pl=deliveryBatch(e,ss,12,false);e.context.syncOfflineBatch(ss.id,pl.inflight);const batch=pairedBatch(e,ss);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,batch.inflight),/API failure/);const fresh=e.context.getBootstrap(ss.id);assert.equal(fresh.stock[0].locationId,'CSFG C1:A1-1');assert.equal(fresh.deliveryNotes[0].lines[0].location,'A1-1');assert.equal(batch.queue.length,1);assert.equal(e.context.syncOfflineBatch(ss.id,batch.inflight).data.stock[0].locationId,'CSFG C1:B2-1');});
test('delivery draft and issue commit atomically with stock and receipt; history survives reload',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const cache=deliveryBatch(e,ss),r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.data.stock[0].qty,23);const loaded=e.context.getBootstrap(ss.id);assert.equal(loaded.deliveryNotes[0].state,'ISSUED');assert.equal(loaded.deliveryNotes[0].lines[0].qty,7);assert.equal(loaded.deliveryNotes[0].note,'=literal destination note');assert.equal(e.sheets.get('Delivery_Notes').getLastRow(),2);assert.equal(e.sheets.get('Delivery_Lines').getLastRow(),2);assert.equal(e.batches(),2);});
test('delivery sync response lost after commit retries without deducting twice',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const cache=deliveryBatch(e,ss);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/lost/);const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.replayed,true);assert.equal(r.data.stock[0].qty,23);assert.equal(r.data.deliveryNotes.length,1);assert.equal(e.batches(),2);assert.equal(e.context.Off.acknowledge(cache,r).queue.length,0);});
test('API failure rolls back delivery, stock and receipt together',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const cache=deliveryBatch(e,ss,30);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/API failure/);let d=e.context.getBootstrap(ss.id);assert.equal(d.stock[0].qty,30);assert.equal(d.deliveryNotes.length,0);e.context.syncOfflineBatch(ss.id,cache.inflight);d=e.context.getBootstrap(ss.id);assert.equal(d.stock.length,0);assert.equal(d.deliveryNotes[0].lines[0].qty,30);});
test('two devices confirming overlapping picks conflict with no second reduction',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const a=deliveryBatch(e,ss,20),b=deliveryBatch(e,ss,20);e.context.syncOfflineBatch(ss.id,a.inflight);const r=e.context.syncOfflineBatch(ss.id,b.inflight);assert.equal(r.conflict,true);const data=e.context.getBootstrap(ss.id);assert.equal(data.stock[0].qty,10);assert.equal(data.deliveryNotes.length,1);assert.equal(e.batches(),2);});
test('synced draft can be confirmed in a later batch after reloading normalized sheets',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);e.context.syncOfflineBatch(ss.id,deliveryBatch(e,ss,7,false).inflight);const O=e.context.Off;let cache=O.initial(e.context.getBootstrap(ss.id));const d=cache.data.deliveryNotes[0];cache=O.enqueue(cache,{version:cache.data.version,action:'issueDelivery',sjNumber:'0000123456',documentId:d.id,documentRevision:d.revision},ss,require('crypto').randomUUID,'2026-09-11T02:00:00.000Z');cache=O.freeze(cache,require('crypto').randomUUID);const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.data.stock[0].qty,23);assert.equal(r.data.deliveryNotes[0].state,'ISSUED');const other=e.context.startSession({...input,mode:'CHILLER'});assert.equal(other.data.deliveryNotes.length,0);});
test('legacy endpoint cannot delete or reduce stock without delivery note',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;const data=save(e,ss);assert.throws(()=>e.context.mutateStock(ss.id,{version:1,action:'delete',ids:[data.stock[0].id]}),/delivery note/);assert.throws(()=>e.context.mutateStock(ss.id,{version:1,action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[{...data.stock[0],qty:2}]}),/delivery note/);assert.equal(e.context.getBootstrap(ss.id).stock[0].qty,30);});

function bulkBatch(e,ss){const O=e.context.Off;let cache=O.initial(e.context.getBootstrap(ss.id));cache=O.enqueue(cache,{version:cache.data.version,action:'bulkReceive',item:row,rows:[{locationId:'CSFG C1:A1-1',qty:30,palletNo:'0031'},{locationId:'CSFG C1:A1-2',qty:18,palletNo:'125'}]},ss,require('crypto').randomUUID,'2026-09-11T01:00:00.000Z');return O.freeze(cache,require('crypto').randomUUID);}
test('bulk sync commits all rack receipts once, and lost-response retry cannot duplicate them',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=bulkBatch(e,ss);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/lost/);const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.replayed,true);assert.equal(r.data.stock.length,2);assert.equal(r.data.stock[0].palletNo,'31');assert.equal(r.data.stock[1].palletNo,'125');assert.equal(e.batches(),1);assert.equal(e.context.Off.acknowledge(cache,r).queue.length,0);});
test('bulk conflict on second rack leaves first rack empty and local outbox intact',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=bulkBatch(e,ss);e.context.mutateStock(ss.id,{version:0,action:'saveSlot',locationId:'CSFG C1:A1-2',functionType:'Reguler',items:[row]});const r=e.context.syncOfflineBatch(ss.id,cache.inflight);assert.equal(r.conflict,true);const d=e.context.getBootstrap(ss.id);assert.equal(d.stock.length,1);assert.equal(d.stock[0].locationId,'CSFG C1:A1-2');assert.equal(cache.queue.length,1);assert.equal(e.batches(),1);});
test('bulk API failure does not persist any of the rack rows or receipt',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session,cache=bulkBatch(e,ss);e.failBatch();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/API failure/);assert.equal(e.context.getBootstrap(ss.id).stock.length,0);assert.equal(e.sheets.get('Sync_Log').getLastRow(),1);assert.equal(cache.queue.length,1);});

test('v1.4 migration appends truck metadata without touching legacy notes, lines or stock',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);e.context.syncOfflineBatch(ss.id,deliveryBatch(e,ss).inflight);const notes=e.sheets.get('Delivery_Notes');notes.rows=notes.rows.map(r=>r.slice(0,16));const before=JSON.stringify(notes.rows),lines=JSON.stringify(e.sheets.get('Delivery_Lines').rows),stock=JSON.stringify(e.sheets.get('Stock_Detail').rows);const loaded=e.context.getBootstrap(ss.id);assert.equal(JSON.stringify(notes.rows.map(r=>r.slice(0,16))),before);assert.deepEqual(Array.from(notes.rows[0].slice(16)),['truck','shift','pickingNumber','sjNumber']);assert.equal(JSON.stringify(e.sheets.get('Delivery_Lines').rows),lines);assert.equal(JSON.stringify(e.sheets.get('Stock_Detail').rows),stock);assert.equal(loaded.deliveryNotes[0].state,'ISSUED');assert.equal(loaded.deliveryNotes[0].truck,'');});

test('v1.4 rejects custom metadata columns before writing any migration header',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;e.context.getBootstrap(ss.id);const notes=e.sheets.get('Delivery_Notes');notes.rows[0]=notes.rows[0].slice(0,16);notes.rows[0][18]='Custom owner data';const before=JSON.stringify(notes.rows);assert.throws(()=>e.context.getBootstrap(ss.id),/Kolom tambahan/);assert.equal(JSON.stringify(notes.rows),before);});

test('truck, shift and picking reference survive a separate sync and reload before issue',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const O=e.context.Off,id=require('crypto').randomUUID(),stamp='2026-09-13T01:00:00.000Z';let cache=O.initial(e.context.getBootstrap(ss.id));cache=O.enqueue(cache,{action:'saveDelivery',version:cache.data.version,documentId:id,documentRevision:0,date:input.date,truck:'B 1234 AB',shift:'S1',destination:'Packing',lines:[{itemId:cache.data.stock[0].id,qty:7}]},ss,require('crypto').randomUUID,stamp);cache=O.freeze(cache,require('crypto').randomUUID);e.context.syncOfflineBatch(ss.id,cache.inflight);let d=e.context.getBootstrap(ss.id),pl=d.deliveryNotes[0].pickingNumber;assert.equal(d.deliveryNotes[0].truck,'B 1234 AB');assert.equal(d.deliveryNotes[0].shift,'S1');assert.match(pl,/^PL-/);assert.equal(d.stock[0].qty,30);cache=O.enqueue(O.initial(d),{action:'issueDelivery',sjNumber:'0000123456',version:d.version,documentId:id,documentRevision:1},ss,require('crypto').randomUUID,stamp);cache=O.freeze(cache,require('crypto').randomUUID);e.context.syncOfflineBatch(ss.id,cache.inflight);e.context.syncOfflineBatch(ss.id,cache.inflight);d=e.context.getBootstrap(ss.id);assert.equal(d.stock[0].qty,23);assert.equal(d.deliveryNotes.length,1);assert.equal(d.deliveryNotes[0].pickingNumber,pl);assert.equal(d.deliveryNotes[0].truck,'B 1234 AB');});

test('v160 additive SJ migration preserves existing rows and lost-response retry records SJ once',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);for(const [name,width] of [['Delivery_Notes',19],['Transaction_Log',23]]){const s=e.sheets.get(name);s.rows=s.rows.map(r=>r.slice(0,width));}const receipt=JSON.stringify(e.sheets.get('Transaction_Log').rows[1]);e.context.getBootstrap(ss.id);e.context.getStockExport(ss.id);assert.equal(e.sheets.get('Delivery_Notes').rows[0][19],'sjNumber');assert.equal(e.sheets.get('Transaction_Log').rows[0][23],'sjNumber');assert.equal(JSON.stringify(e.sheets.get('Transaction_Log').rows[1]),receipt);const cache=deliveryBatch(e,ss,12);e.loseReply();assert.throws(()=>e.context.syncOfflineBatch(ss.id,cache.inflight),/lost/);e.context.syncOfflineBatch(ss.id,cache.inflight);const d=e.context.getBootstrap(ss.id);assert.equal(d.stock[0].qty,18);assert.equal(d.deliveryNotes[0].sjNumber,'0000123456');const rows=e.context.getStockExport(ss.id).rows.filter(r=>r.type==='OUT');assert.equal(rows.length,1);assert.equal(rows[0].sjNumber,'0000123456');assert.equal(rows[0].itemId,d.stock[0].id);});
test('v160 custom columns in new SJ positions are rejected without overwriting',()=>{for(const [name,index] of [['Delivery_Notes',19],['Transaction_Log',23]]){const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;e.context.getStockExport(ss.id);const s=e.sheets.get(name);s.rows[0][index]='Custom';assert.throws(()=>name==='Delivery_Notes'?e.context.getBootstrap(ss.id):e.context.getStockExport(ss.id),/Kolom tambahan/);assert.equal(s.rows[0][index],'Custom');}});

test('export exposes the schema version used by the paired workbook',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;assert.equal(e.context.getStockExport(ss.id).schema,'coldstock-excel-162');});

test('approved 79/76 repair preserves30, splits identities and can be rerun safely',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const id='bb6eeeed-2761-40c1-adbe-01f478f0f15d',stock=e.sheets.get('Stock_Detail').rows[1];stock[0]=id;stock[2]='PCN';stock[3]='2026-09-28';stock[4]='2026-09-28';stock[5]=30;stock[8]='Hold';stock[12]='104';const fields=vm.runInContext('StockExport.fields',e.context),base=e.context.getStockExport(ss.id).rows[0],ledger=e.sheets.get('Transaction_Log');ledger.rows=[Array.from(fields),...['CCN','CCS'].map((sku,n)=>fields.map(k=>({...base,id:'IN-test-'+n,itemId:id,sku,kp:'2026-09-28',palletNo:n?'76':'79',status:'Release',qty:n?20:10})[k]??''))];e.context.repairPallet79And76_();let data=e.context.getBootstrap(ss.id);assert.equal(data.stock.length,2);assert.equal(data.stock.reduce((n,i)=>n+i.qty,0),30);assert.deepEqual(Array.from(data.stock,i=>i.qty),[10, 20]);assert.equal(new Set(data.stock.map(i=>i.id)).size,2);const before=ledger.getLastRow();e.context.repairPallet79And76_();assert.equal(ledger.getLastRow(),before);assert.equal(e.context.getStockExport(ss.id).rows.filter(r=>r.type==='IN').reduce((n,r)=>n+r.qty,0),30);});

test('approved 3/97 repair preserves30, splits identities and can be rerun safely',()=>{const e=env();e.context.setupDatabase_();const ss=e.context.startSession(input).session;save(e,ss);const id='0a9fd36c-28a9-44d8-9908-2c22e76ca3a9',stock=e.sheets.get('Stock_Detail').rows[1];stock[0]=id;stock[2]='PCN';stock[3]='2026-09-28';stock[4]='2026-09-28';stock[5]=30;stock[8]='Hold';stock[12]='104';const fields=vm.runInContext('StockExport.fields',e.context),base=e.context.getStockExport(ss.id).rows[0],ledger=e.sheets.get('Transaction_Log');ledger.rows=[Array.from(fields),...['CCN','CCS'].map((sku,n)=>fields.map(k=>({...base,id:'IN-test-'+n,itemId:id,sku,kp:'2026-09-28',palletNo:n?'97':'3',status:'Release',qty:n?15:15})[k]??''))];e.context.repairPallet3And97_();let data=e.context.getBootstrap(ss.id);assert.equal(data.stock.length,2);assert.equal(data.stock.reduce((n,i)=>n+i.qty,0),30);assert.deepEqual(Array.from(data.stock,i=>i.qty),[15, 15]);assert.equal(new Set(data.stock.map(i=>i.id)).size,2);const before=ledger.getLastRow();e.context.repairPallet3And97_();assert.equal(ledger.getLastRow(),before);assert.equal(e.context.getStockExport(ss.id).rows.filter(r=>r.type==='IN').reduce((n,r)=>n+r.qty,0),30);});
