const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),{randomUUID}=require('crypto');
const c=vm.createContext({Date,Map,Set,JSON});for(const f of ['layout','core','delivery','offline','excel-export'])vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),c);
const [W,D,O,E]=vm.runInContext('[WMS,Delivery,Offline,StockExport]',c),ss={id:randomUUID(),mode:'CSFG',date:'2026-09-30',shift:'S1',name:'QA'},now='2026-09-30T04:00:00Z';
const data=()=>{const d={version:0,stock:[],locations:c.defaultLocations_(),skus:W.SKU,deliveryNotes:[]};return D.mutate(d,{version:0,action:'bulkReceive',item:{sku:'CCN',kp:ss.date,status:'Release',spv:'AK'},rows:[{locationId:'CSFG C1:A1-1',qty:30,palletNo:'31'}]},ss,randomUUID,now);};
const req=(d,patch={qty:25})=>({version:d.version,action:'correctItem',itemId:d.stock[0].id,before:{...d.stock[0]},item:{...d.stock[0],...patch},reason:'Salah input awal'});
test('correction 30 to25 has stable identity, delta -5, immutable receipt and full audit',()=>{const d=data(),r=req(d),out=D.mutate(d,r,ss,randomUUID,now),rows=E.capture(d,out,r,ss,randomUUID(),now);a.equal(d.stock[0].qty,30);a.equal(out.stock[0].qty,25);a.equal(out.stock[0].id,d.stock[0].id);a.equal(rows.length,1);a.equal(rows[0].type,'KOREKSI');a.equal(rows[0].qty,-5);a.equal(JSON.parse(rows[0].beforeJson).qty,30);a.equal(rows[0].reason,r.reason);a.equal(rows[0].name,ss.name);a.equal(E.values(rows[0]).length,25);});
test('identity edits require correction; correcting SKU is not a second IN',()=>{const d=data(),item={...d.stock[0],sku:'PCN'};a.throws(()=>D.mutate(d,{version:d.version,action:'saveSlot',locationId:item.locationId,functionType:'Reguler',items:[item]},ss,randomUUID,now),/Koreksi/);const r=req(d,{sku:'PCN',kp:'2026-09-29',palletNo:'99',spv:'HW'}),out=D.mutate(d,r,ss,randomUUID,now);a.equal(out.stock[0].sku,'PCN');a.equal(E.capture(d,out,r,ss,randomUUID(),now)[0].qty,0);});
test('missing reason, invalid quantity, stale version and wrong warehouse are rejected',()=>{const d=data();for(const patch of [{reason:''},{version:0},{item:{...d.stock[0],qty:-1}},{item:{...d.stock[0],qty:2.5}}])a.throws(()=>D.mutate(d,{...req(d),...patch},ss,randomUUID,now));a.throws(()=>D.mutate(d,req(d),{...ss,mode:'CHILLER'},randomUUID,now));});
test('reservation protects quantities and identity, while quantity correction can retain valid allocation',()=>{let d=data();d=D.mutate(d,{version:d.version,action:'saveDelivery',documentId:randomUUID(),documentRevision:0,date:ss.date,destination:'DC',lines:[{itemId:d.stock[0].id,qty:26}]},ss,randomUUID,now);a.throws(()=>D.mutate(d,req(d),ss,randomUUID,now),/alokasi/);a.equal(D.mutate(d,req(d,{qty:28}),ss,randomUUID,now).stock[0].qty,28);a.throws(()=>D.mutate(d,req(d,{sku:'PCN'}),ss,randomUUID,now),/draft/);});
test('issued history is immutable and prevents identity rewrite but permits remaining quantity correction',()=>{let d=data();d=D.mutate(d,{version:d.version,action:'saveDelivery',documentId:randomUUID(),documentRevision:0,date:ss.date,destination:'DC',lines:[{itemId:d.stock[0].id,qty:10}]},ss,randomUUID,now);d=D.mutate(d,{version:d.version,action:'issueDelivery',documentId:d.deliveryNotes[0].id,documentRevision:1,sjNumber:'000123'},ss,randomUUID,now);const old=JSON.stringify(d.deliveryNotes);a.throws(()=>D.mutate(d,req(d,{sku:'PCN'}),ss,randomUUID,now),/pengiriman/);const out=D.mutate(d,req(d,{qty:15}),ss,randomUUID,now);a.equal(JSON.stringify(out.deliveryNotes),old);a.equal(out.stock[0].qty,15);});
test('correction persists offline, replays deterministically and acknowledges exactly once',()=>{const d=data(),st=O.enqueue(O.initial(d),req(d),ss,randomUUID,now),saved=JSON.parse(JSON.stringify(st)),next=O.apply(d,saved.queue[0],ss);a.equal(next.stock[0].qty,25);const frozen=O.freeze(saved,randomUUID),ack=O.acknowledge(frozen,{batchId:frozen.inflight.id,ackIds:[saved.queue[0].id],data:next});a.equal(ack.queue.length,0);a.equal(Object.keys(saved.queue[0].expected).length,1);});
test('legacy CCN16 PCN14 get separate stable report keys; OUT follows source SKU and total stays30',()=>{const d=data(),base={id:'one',itemId:'e8113d62-4f51-46f3-bb65-c70b1a9a5afe',mode:ss.mode,date:ss.date,at:now,sku:'CCN',kp:ss.date,palletNo:'104',qty:16,type:'IN',unit:'CTN'},rows=[base,{...base,id:'two',sku:'PCN',qty:14},{...base,id:'out',type:'OUT',sku:'PCN',qty:2}];const out=E.allRows(rows,[],[],ss.mode);a.notEqual(out[0].itemId,out[2].itemId);const p=out.find(r=>r.id==='two'),shipment=out.find(r=>r.id==='out');a.equal(p.itemId,shipment.itemId);a.equal(out.filter(r=>r.type==='IN').reduce((n,r)=>n+r.qty,0),30);a.equal(rows[0].itemId,rows[1].itemId);});

test('stale correction snapshot cannot overwrite a later edit even if version is refreshed',()=>{const d=data(),r=req(d);d.stock[0].note='Updated by another operator';r.version=d.version;a.throws(()=>D.mutate(d,r,ss,randomUUID,now),/formulir/);});
