const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{randomUUID}=require('node:crypto');
const ctx=vm.createContext({console,Date,Map,Set,JSON});for(const f of ['layout','core','delivery','offline'])vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),ctx);vm.runInContext('this.D=Delivery;this.W=WMS;this.O=Offline;',ctx);const {D,W,O}=ctx;
const ss={id:randomUUID(),name:'SK Trial',date:'2026-09-11',shift:'S1',mode:'CSFG'},now='2026-09-11T01:00:00.000Z';
const empty=()=>({locations:ctx.defaultLocations_(),skus:W.SKU,stock:[],version:0});
const run=(data,request,actor=ss)=>D.mutate(data,{version:data.version,...request},actor,randomUUID,now);
const raw={sku:'CCN',kp:'2026-09-11',qty:30,unit:'CTN',spv:'HW',status:'Release',palletNo:'0031',note:'=literal'};
const stock=()=>run(empty(),{action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items:[raw,{...raw,sku:'PCN',qty:20,palletNo:'0009'}]});
const draft=(data,lines=[{itemId:data.stock[0].id,qty:7}])=>run(data,{action:'saveDelivery',documentId:randomUUID(),documentRevision:0,date:ss.date,destination:'Packing A',note:'Trial',lines});
const issue=(data,d=data.deliveryNotes[0])=>run(data,{action:'issueDelivery',sjNumber:'0000123456',documentId:d.id,documentRevision:d.revision});

test('30 CTN split 12 and 10 reserves 22, leaves 8, and either issue order preserves the other truck',()=>{for(const order of [[0,1],[1,0]]){let d=stock(),id=d.stock[0].id;d=draft(d,[{itemId:id,qty:12}]);d=draft(d,[{itemId:id,qty:10}]);assert.equal(D.availability(d,id).physical,30);assert.equal(D.availability(d,id).reserved,22);assert.equal(D.availability(d,id).available,8);d=issue(d,d.deliveryNotes[order[0]]);assert.equal(D.availability(d,id).available,8);assert.equal(D.availability(d,id).reserved,order[0]===0?10:12);d=issue(d,d.deliveryNotes[order[1]]);assert.equal(D.availability(d,id).physical,8);assert.equal(D.availability(d,id).reserved,0);assert.equal(D.availability(d,id).available,8);}});

test('editing uses own reservation, releases removed quantities and cancellation releases the rest',()=>{let d=stock(),id=d.stock[0].id;d=draft(d,[{itemId:id,qty:12},{itemId:d.stock[1].id,qty:6}]);d=draft(d,[{itemId:id,qty:10}]);let a=d.deliveryNotes[0];assert.equal(D.availability(d,id,a.id).available,20);const req={action:'saveDelivery',documentId:a.id,documentRevision:a.revision,date:ss.date,destination:'A',lines:[{itemId:id,qty:21}]};assert.throws(()=>run(d,req),/Sisa tersedia.*20 CTN/);d=run(d,{...req,lines:[{itemId:id,qty:5}]});assert.equal(D.availability(d,id).available,15);assert.equal(D.availability(d,d.stock[1].id).reserved,0);a=d.deliveryNotes[0];d=run(d,{action:'cancelDelivery',documentId:a.id,documentRevision:a.revision});assert.equal(D.availability(d,id).available,20);assert.equal(D.availability(d,id).physical,30);});

test('reservations span dates and shifts but never pool separate items sharing the pallet number',()=>{let d=stock(),id=d.stock[0].id;d.stock[1].palletNo=d.stock[0].palletNo;d=draft(d,[{itemId:id,qty:30}]);d.deliveryNotes[0].date='2020-01-01';d.deliveryNotes[0].shift='S3';assert.equal(D.availability(d,id).available,0);assert.equal(D.availability(d,d.stock[1].id).available,20);assert.throws(()=>draft(d,[{itemId:id,qty:1}]),/Sisa tersedia.*0 CTN/);});

test('legacy overallocated drafts remain visible and cancellable but cannot consume another reservation',()=>{let d=stock(),id=d.stock[0].id;d=draft(d,[{itemId:id,qty:20}]);const legacy=JSON.parse(JSON.stringify(d.deliveryNotes[0]));legacy.id=randomUUID();d.deliveryNotes.push(legacy);assert.equal(D.availability(d,id).overbooked,true);assert.equal(D.availability(d,id).available,0);assert.throws(()=>issue(d),/Alokasi picking melebihi/);assert.equal(d.stock[0].qty,30);d=run(d,{action:'cancelDelivery',documentId:legacy.id,documentRevision:legacy.revision});d=issue(d);assert.equal(d.stock[0].qty,10);});

test('failed offline overallocation leaves the durable queue unchanged; restored drafts still reserve',()=>{let initial=stock(),state=O.initial(initial),id=initial.stock[0].id;const request=q=>({action:'saveDelivery',documentId:randomUUID(),documentRevision:0,date:ss.date,destination:'A',lines:[{itemId:id,qty:q}]});state=O.enqueue(state,{...request(12),version:state.data.version},ss,randomUUID,now);state=JSON.parse(JSON.stringify(state));state=O.enqueue(state,{...request(10),version:state.data.version},ss,randomUUID,now);const before=JSON.stringify(state);assert.throws(()=>O.enqueue(state,{...request(9),version:state.data.version},ss,randomUUID,now),/Sisa tersedia.*8 CTN/);assert.equal(JSON.stringify(state),before);let server=initial;for(const op of state.queue)server=O.apply(server,op,ss);assert.equal(D.availability(server,id).available,8);state=O.freeze(state,randomUUID);state=O.acknowledge(state,{batchId:state.inflight.id,ackIds:state.queue.map(o=>o.id),data:server});assert.equal(state.queue.length,0);assert.equal(D.availability(state.data,id).reserved,22);});
test('draft snapshots reserve quantity without reducing physical stock',()=>{const before=stock(),after=draft(before);assert.equal(after.stock[0].qty,30);assert.equal(D.availability(after,after.stock[0].id).available,23);assert.equal(before.deliveryNotes,undefined);assert.equal(after.deliveryNotes[0].state,'DRAFT');assert.equal(after.deliveryNotes[0].lines[0].palletNo,'31');assert.equal(after.deliveryNotes[0].lines[0].note,'=literal');});
test('issuing partial quantity preserves ID and other item and records operator',()=>{const data=draft(stock()),id=data.stock[0].id,after=issue(data);assert.equal(after.stock[0].id,id);assert.equal(after.stock[0].qty,23);assert.equal(after.stock[1].qty,20);assert.equal(after.deliveryNotes[0].state,'ISSUED');assert.equal(after.deliveryNotes[0].confirmedName,ss.name);assert.equal(data.stock[0].qty,30);});
test('full issue removes stock item while retaining immutable line history',()=>{const before=stock(),after=issue(draft(before,[{itemId:before.stock[0].id,qty:30}]));assert.equal(after.stock.length,1);assert.equal(after.deliveryNotes[0].lines[0].qty,30);assert.equal(after.deliveryNotes[0].lines[0].location,'A1-1');assert.throws(()=>issue(after),/sudah diproses/);assert.throws(()=>run(after,{action:'cancelDelivery',documentId:after.deliveryNotes[0].id,documentRevision:2}),/sudah diproses/);});
test('cancelled draft stays in history without affecting inventory',()=>{const data=draft(stock()),after=run(data,{action:'cancelDelivery',documentId:data.deliveryNotes[0].id,documentRevision:1});assert.equal(after.stock[0].qty,30);assert.equal(after.deliveryNotes[0].state,'CANCELLED');});
test('second draft cannot reserve more than the remainder',()=>{let data=stock();data=draft(data,[{itemId:data.stock[0].id,qty:20}]);const before=JSON.stringify(data);assert.throws(()=>draft(data,[{itemId:data.stock[0].id,qty:20}]),/Sisa tersedia.*10 CTN/);assert.equal(JSON.stringify(data),before);});
test('all lines validate before any quantity changes',()=>{let data=stock();data=draft(data,data.stock.map(i=>({itemId:i.id,qty:15})));data.stock[1].qty=10;assert.throws(()=>issue(data),/tidak cukup/);assert.equal(data.stock[0].qty,30);assert.equal(data.deliveryNotes[0].state,'DRAFT');});
test('moving item or changing KP after draft requires updating draft',()=>{let data=draft(stock());data=run(data,{action:'move',ids:[data.stock[0].id],destination:'WIP-CSFG'});assert.throws(()=>issue(data),/berubah sejak/);});
test('draft edit revision is checked and current stock is resnapshotted',()=>{let data=draft(stock()),doc=data.deliveryNotes[0];const req={action:'saveDelivery',documentId:doc.id,documentRevision:1,date:ss.date,destination:'Tujuan B',note:'',lines:[{itemId:data.stock[0].id,qty:12}]};data=run(data,req);assert.equal(data.deliveryNotes[0].revision,2);assert.equal(data.deliveryNotes[0].lines[0].qty,12);assert.throws(()=>run(data,req),/CONFLICT/);});
test('invalid quantities, duplicate IDs and cross-mode requests rejected',()=>{const data=stock();for(const qty of [0,-1,1.5,31,Infinity])assert.throws(()=>draft(data,[{itemId:data.stock[0].id,qty}]));assert.throws(()=>draft(data,[{itemId:data.stock[0].id,qty:1},{itemId:data.stock[0].id,qty:1}]),/duplikat/);const d=draft(data);assert.throws(()=>run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:d.deliveryNotes[0].id,documentRevision:1},{...ss,mode:'CHILLER'}),/luar area/);});
test('direct delete, omission, qty decrease and unit conversion cannot bypass history',()=>{const data=stock();assert.throws(()=>run(data,{action:'delete',ids:[data.stock[0].id]}),/delivery note/);for(const items of [[],[{...data.stock[0],qty:10},data.stock[1]],[{...data.stock[0],unit:'PACK'},data.stock[1]]])assert.throws(()=>run(data,{action:'saveSlot',locationId:'CSFG C1:A1-1',functionType:'Reguler',items}));});
test('picklist text separates units and retains pallet, KP, SPV and status',()=>{const data=draft(stock()),doc=data.deliveryNotes[0];assert.match(D.text(doc),/BELUM MENGURANGI STOK/);assert.match(D.text(doc),/Pallet 31/);assert.match(D.text(doc),/KP 2026-09-11/);assert.match(D.text(doc),/SPV HW/);assert.match(D.text(doc),/Total: 7 CTN/);assert.match(D.text(issue(data).deliveryNotes[0]),/BARANG KELUAR/);});
test('offline create and issue replay together with document conflict fingerprints',()=>{const initial=stock();let state=O.initial(initial);const id=randomUUID();for(const req of [{action:'saveDelivery',documentId:id,documentRevision:0,date:ss.date,destination:'Packing',note:'',lines:[{itemId:initial.stock[0].id,qty:7}]},{action:'issueDelivery',sjNumber:'0000123456',documentId:id,documentRevision:1}])state=O.enqueue(state,{version:state.data.version,...req},ss,randomUUID,now);let server=initial;for(const op of state.queue){for(const key of O.touched(server,op.request))assert.equal(O.fingerprint(server,key),op.expected[key]);server=O.apply(server,op,ss);}assert.equal(server.stock[0].qty,23);assert.equal(server.deliveryNotes[0].state,'ISSUED');state=O.freeze(state,randomUUID);const ack=O.acknowledge(state,{batchId:state.inflight.id,ackIds:state.queue.map(o=>o.id),data:server});assert.equal(ack.queue.length,0);assert.equal(ack.data.deliveryNotes[0].lines[0].qty,7);});

test('v160 SJ is required only at final issue and rejects invalid input without changing stock',()=>{const data=draft(stock()),before=JSON.stringify(data),doc=data.deliveryNotes[0];for(const sjNumber of [undefined,'', '   ',12345,'a'.repeat(81),'A\tB','A\nB']){assert.throws(()=>run(data,{action:'issueDelivery',documentId:doc.id,documentRevision:1,sjNumber}),/SJ/);assert.equal(JSON.stringify(data),before);}const after=run(data,{action:'issueDelivery',documentId:doc.id,documentRevision:1,sjNumber:' 0000123456 '});assert.equal(after.deliveryNotes[0].sjNumber,'0000123456');assert.equal(after.stock[0].qty,23);assert.match(D.text(after.deliveryNotes[0]),/No. SJ: 0000123456/);});
test('v160 blank legacy SJ keeps draft fingerprint compatible and never impersonates SAP SJ',()=>{const data=draft(stock()),doc=data.deliveryNotes[0],old=JSON.stringify([D.fields.slice(0,19).map(k=>doc[k]??''),doc.lines.map(l=>D.lineFields.slice(0,13).map(k=>l[k]??''))]);assert.equal(D.fingerprint(data,doc.id),old);doc.sjNumber='';assert.equal(D.fingerprint(data,doc.id),old);doc.state='ISSUED';assert.match(D.text(doc),/SJ: Belum tercatat/);assert.match(D.text(doc),/Referensi internal:/);});
