const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),{randomUUID}=require('crypto');
const ctx=vm.createContext({Date,Map,Set,JSON});for(const f of ['core','excel-export'])vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),ctx);const E=vm.runInContext('StockExport',ctx);
const actor={id:randomUUID(),mode:'CSFG',date:'2026-09-22',shift:'S3',name:'SK Test'},at='2026-09-22T18:00:00Z';
const loc={id:'CSFG C1:A1-1',group:'CSFG',room:'CSFG C1'},item={id:randomUUID(),locationId:loc.id,sku:'CCN',kp:'2026-09-20',palletNo:'31',qty:30,unit:'CTN',status:'Hold',note:'QC'},empty={stock:[],locations:[loc]},data={stock:[item],locations:[loc]};
const receipt=()=>E.capture(empty,data,{action:'saveSlot'},actor,'operation-1',at)[0];
test('IN captures original status and receipt quantity, not stock snapshots',()=>{const r=receipt();assert.equal(r.qty,30);assert.equal(r.status,'Hold');assert.equal(r.date,actor.date);const increased={...data,stock:[{...item,qty:38,status:'Release'}]};const delta=E.capture(data,increased,{action:'saveSlot'},actor,'increase-2',at);assert.equal(delta.length,1);assert.equal(delta[0].qty,8);assert.equal(r.status,'Hold');assert.equal(E.capture(data,{...data,stock:[{...item,status:'Release'}]},{action:'saveSlot'},actor,'edit',at).length,0);assert.equal(E.capture(data,increased,{action:'moveBatch'},actor,'move',at).length,0);});
test('master contains all 20 user products and maps known old codes without renaming stock',()=>{assert.equal(E.master.length,20);assert.equal(new Set(E.master.map(r=>r[0])).size,20);assert.equal(E.product('SH')[0],'KM-053');assert.equal(E.product('KM-070')[1],'CHICKEN WINGS');assert.equal(E.product('SOSIS TOMYUM')[0],'KM-071');assert.equal(E.product('not-known'),null);});
test('IN and OUT have distinct agreed columns with QTY after KP and stable trace identity',()=>{const r=receipt(),input=E.tsv([r],'IN',true).split('\r\n').map(l=>l.split('\t'));assert.equal(input[0].length,14);assert.equal(input[1][2],'KM-038');assert.equal(input[1][6],'31');assert.equal(input[1][5],'30');const out={...r,type:'OUT',documentNo:'DN-1',truck:'B 1234 AA',destination:'DC'};assert.equal(E.values(out)[5],30);assert.equal(E.headers.OUT[5],'QTY');assert.equal(E.tsv([out],'OUT',false).split('\t').length,18);assert.throws(()=>E.tsv([r],'OUT',true),/tercampur/);});
test('export filters operational date and mode, shift, original room without altering rows',()=>{const rows=[receipt(),{...receipt(),id:'another',date:'2026-09-21',shift:'S1'}, {...receipt(),id:'foreign',mode:'CHILLER'}],before=JSON.stringify(rows);assert.equal(E.select(rows,'CSFG',{type:'IN',from:actor.date,to:actor.date,shift:'S3',room:loc.room}).length,1);assert.equal(E.select(rows,'CSFG',{type:'IN'}).length,2);assert.equal(E.select(rows,'CSFG',{type:'OUT'}).length,0);assert.throws(()=>E.select(rows,'CSFG',{type:'IN',from:'2026-09-23',to:'2026-09-22'}));assert.throws(()=>E.select(rows,'CSFG',{type:'IN',from:'2026-02-30'}));assert.equal(JSON.stringify(rows),before);});
test('TSV cannot inject formulas or extra rows/columns and preserves long pallet identifiers',()=>{const r={...receipt(),type:'OUT',palletNo:'99999999999999999999',destination:'\t=HYPERLINK("bad")\r\nnext',truck:'+formula',documentNo:'@bad'};const line=E.tsv([r],'OUT',false);assert.equal(line.split('\r\n').length,1);assert.equal(line.split('\t').length,18);assert.equal(line.split('\t')[6],"'99999999999999999999");assert(line.includes("'=HYPERLINK"));assert(line.includes("'+formula"));assert(line.includes("'@bad"));});
test('unmapped SKU and PACK cannot silently export wrong product or CTN quantity',()=>{assert.throws(()=>E.tsv([{...receipt(),sku:'unknown'}],'IN',false),/dipetakan/);assert.throws(()=>E.tsv([{...receipt(),unit:'PACK'}],'IN',false),/CTN/);});
test('quoted formula-looking text is neutralized before Excel can unquote it',()=>{assert.equal(E.cell('"=1+1"'),"'\"=1+1\"");assert.equal(E.cell('\ufeff=1+1'),"'=1+1");});
test('issued old documents survive zero stock, drafts excluded and IDs stable across repeated loads',()=>{const doc={id:randomUUID(),number:'DN-old',mode:'CSFG',state:'ISSUED',confirmedAt:at,confirmedBy:actor.id,shift:'S1',date:'2026-09-19',lines:[{...item,room:loc.room,qty:12,itemId:item.id}]};let rows=E.allRows([receipt()],[doc,{...doc,id:'draft',state:'DRAFT'}],[actor],'CSFG');assert.equal(rows.length,2);const out=rows.find(r=>r.type==='OUT');assert.equal(out.date,actor.date);assert.equal(out.shift,'S3');assert.equal(out.qty,12);assert.equal(E.allRows(rows,[doc],[actor],'CSFG').length,2);const missing=E.allRows([],[doc],[],'CSFG')[0];assert.equal(missing.shift,'');assert.equal(missing.date,'2026-09-23');assert.equal(E.allRows([],[doc],[],'CHILLER').length,0);});
test('copy includes all results beyond 100 preview rows; unique IDs permit duplicate detection',()=>{const rows=Array.from({length:130},(_,n)=>({...receipt(),id:'IN-'+n}));assert.equal(E.tsv(rows,'IN',false).split('\r\n').length,130);assert.throws(()=>E.allRows([receipt(),receipt()],[],[],actor.mode),/duplikat/);});
test('all shipped inline scripts parse and server avoids unsupported logical assignment',()=>{const html=fs.readFileSync('Index.html','utf8');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);new vm.Script(fs.readFileSync('Code.gs','utf8'));assert.doesNotMatch(fs.readFileSync('Code.gs','utf8'),/(\?\?|\|\||&&)=/);});

test('v160 exports source identity separately from combined physical label and preserves SJ zeros',()=>{const row={...receipt(),type:'OUT',sjNumber:'0000123456',documentNo:'DN-internal',palletNo:'47',palletLabel:'47,48',palletId:'physical-1',truck:'B 1234 AA',destination:'DC'};const v=E.values(row);assert.equal(v[6],'47');assert.equal(v[7],'47,48');assert.equal(v[9],'0000123456');assert.equal(v[12],item.id);assert.equal(v[14],'physical-1');assert.equal(v[15],'DN-internal');assert.equal(E.tsv([row],'OUT',false).split('\t')[9],"'0000123456");assert.equal(E.values({...row,sjNumber:''})[9],'');});
