const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('vm'),fs=require('fs'),{randomUUID}=require('crypto');
const c=vm.createContext({console,Date,Map,Set,JSON});for(const file of ['layout','core','delivery','offline','picking','excel-export'])vm.runInContext(fs.readFileSync('src/'+file+'.js','utf8'),c);
const W=vm.runInContext('WMS',c),D=vm.runInContext('Delivery',c),O=vm.runInContext('Offline',c),P=vm.runInContext('Pallets',c),K=vm.runInContext('Picking',c),E=vm.runInContext('StockExport',c);
const ss={id:randomUUID(),name:'QA Pallet',mode:'CSFG',shift:'S1',date:'2026-09-23'},at='2026-09-23T02:00:00Z';
const run=(d,r)=>D.mutate(d,{...r,version:d.version},ss,randomUUID,at);
function start(){return run({stock:[],locations:c.defaultLocations_(),skus:W.SKU,version:0},{action:'bulkReceive',item:{sku:'CCN',kp:'2026-09-21',spv:'AK',status:'Release',note:'Receh'},rows:[{locationId:'CSFG C1:A1-1',qty:30,palletNo:'47'},{locationId:'CSFG C1:A1-3',qty:5,palletNo:'48'},{locationId:'CSFG C1:A1-2',qty:3,palletNo:'52'}]});}
const merge=(d,ids=d.stock.map(i=>i.id),destination='CSFG C1:B1-1')=>run(d,{action:'mergePallet',ids,destination});
const pick=(d,lines,id=randomUUID())=>run(d,{action:'saveDelivery',documentId:id,documentRevision:0,date:ss.date,shift:ss.shift,truck:'B 123 AA',destination:'Truk A',lines});
test('three identities become one physical pallet without losing source quantities or creating IN/OUT',()=>{const before=start(),copy=JSON.stringify(before),r={action:'mergePallet',ids:before.stock.map(i=>i.id),destination:'CSFG C1:B1-1'},after=run(before,r);assert.equal(JSON.stringify(before),copy);assert.equal(P.count(after.stock),1);assert.equal(after.stock.length,3);assert.deepEqual(Array.from(after.stock,i=>[i.palletNo,i.qty]),[['47',30],['48',5],['52',3]]);assert(after.stock.every(i=>i.palletLabel==='47,48,52'&&i.locationId===r.destination));assert.equal(new Set(after.stock.map(i=>i.palletId)).size,1);assert.equal(E.capture(before,after,r,ss,randomUUID(),at).length,0);});
test('merge may use selected occupied rack but cannot absorb unrelated stock silently',()=>{const d=start();assert.equal(merge(d,d.stock.map(i=>i.id),d.stock[0].locationId).stock[2].locationId,d.stock[0].locationId);assert.throws(()=>merge(d,d.stock.slice(0,2).map(i=>i.id),d.stock[2].locationId),/barang lain/);});
test('invalid SKU KP status mode number and duplicate ids reject entire merge',()=>{for(const patch of [{sku:'PCN'},{kp:'2025-09-21'},{status:'Hold'},{unit:'PACK'},{palletNo:''}]){const d=start();Object.assign(d.stock[1],patch);const before=JSON.stringify(d);assert.throws(()=>merge(d));assert.equal(JSON.stringify(d),before);}const d=start();assert.throws(()=>merge(d,[d.stock[0].id,d.stock[0].id]));assert.throws(()=>merge(d,d.stock.map(i=>i.id),'CHILLER C1:A1-1'));});
test('existing combined pallet can combine again only with all remaining components',()=>{let d=start();d=merge(d,d.stock.slice(0,2).map(i=>i.id));assert.throws(()=>merge(d,[d.stock[0].id,d.stock[2].id],'CSFG C1:B1-3'),/seluruh komponen/);d=merge(d,d.stock.map(i=>i.id),'CSFG C1:B1-3');assert.equal(P.count(d.stock),1);assert.equal(d.stock[0].palletLabel,'47,48,52');});
test('partial pick and remaining stock both count as one pallet; two trucks count separately',()=>{let d=merge(start());const a=randomUUID(),b=randomUUID();d=pick(d,[{itemId:d.stock[0].id,qty:12},{itemId:d.stock[1].id,qty:2}],a);d=pick(d,[{itemId:d.stock[0].id,qty:10}],b);assert.equal(K.summary(D.find(d,a).lines)[0].pallets,1);assert.equal(K.summary(D.find(d,a).lines)[0].qty,14);assert.equal(P.count(D.find(d,b).lines),1);d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:a,documentRevision:1});assert.equal(P.count(d.stock),1);assert.equal(d.stock.find(i=>i.palletNo==='47').qty,18);assert.equal(d.stock.find(i=>i.palletNo==='48').qty,3);assert.equal(D.availability(d,d.stock[0].id).reserved,10);assert.equal(K.summary(D.find(d,a).lines)[0].pallets,1);});
test('merge updates open picking locations and physical identity, keeps issued snapshots immutable',()=>{let d=start();d=pick(d,[{itemId:d.stock[0].id,qty:2}]);const issued=d.deliveryNotes[0].id;d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:issued,documentRevision:1});const history=JSON.stringify(D.find(d,issued));const draft=randomUUID();d=pick(d,[{itemId:d.stock[0].id,qty:12},{itemId:d.stock[1].id,qty:5}],draft);d=merge(d);assert.equal(JSON.stringify(D.find(d,issued)),history);assert.equal(P.count(D.find(d,draft).lines),1);assert.equal(D.find(d,draft).revision,2);d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:draft,documentRevision:2});assert.equal(d.stock.length,2);});
test('ordinary movement preserves group and rejects splitting members across destinations',()=>{const d=merge(start()),rows=d.stock.map(i=>({itemId:i.id,from:i.locationId,destination:'CSFG C1:C1-1'}));const moved=run(d,{action:'moveBatch',rows});assert.equal(P.count(moved.stock),1);assert(moved.stock.every(i=>i.locationId==='CSFG C1:C1-1'));assert.throws(()=>run(d,{action:'moveBatch',rows:rows.slice(0,1)}),/seluruh komponen/);rows[1].destination='CSFG C1:C1-3';assert.throws(()=>run(d,{action:'moveBatch',rows}),/utuh/);});
test('editing notes retains membership; status changes apply to all components; numbers cannot be overwritten',()=>{const d=merge(start()),r={action:'saveSlot',locationId:d.stock[0].locationId,functionType:'Reguler',items:d.stock.map(i=>({...i,note:'Checked'}))};assert.equal(P.count(run(d,r).stock),1);r.items[0].status='Hold';assert.throws(()=>run(d,r),/seluruh pallet/);r.items.forEach(i=>i.status='Hold');assert(run(d,r).stock.every(i=>i.status==='Hold'));r.items[0].palletNo='100';assert.throws(()=>run(d,r),/Identitas|Koreksi data/);});
test('offline group ID is stable across replay, fingerprints cover source destination and affected picking',()=>{let d=start();d=pick(d,[{itemId:d.stock[0].id,qty:12}]);let state=O.enqueue(O.initial(d),{action:'mergePallet',ids:d.stock.map(i=>i.id),destination:'CSFG C1:B1-1',version:d.version},ss,randomUUID,at);const op=state.queue[0];assert(op.request.palletId);assert.equal(Object.keys(op.expected).length,5);const replay=O.apply(d,op,ss);assert.equal(JSON.stringify(replay),JSON.stringify(state.data));assert.equal(P.count(replay.stock),1);});
test('OUT retains source quantity but presents combined identity in Excel',()=>{let d=merge(start());d=pick(d,[{itemId:d.stock[0].id,qty:12},{itemId:d.stock[1].id,qty:5}]);const before=d,id=d.deliveryNotes[0].id;d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:id,documentRevision:1});const rows=E.capture(before,d,{action:'issueDelivery',sjNumber:'0000123456',documentId:id},ss,randomUUID(),at);assert.equal(rows.length,2);assert.equal(rows[0].palletNo,'47');assert.equal(rows[1].palletNo,'48');assert.equal(E.values(rows[0])[7],'47,48,52');assert.equal(rows[0].qty,12);assert.equal(P.count(d.deliveryNotes[0].lines),1);});

