const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),{randomUUID}=require('crypto');
test('Apps Script bundle avoids logical assignment rejected by its editor parser',()=>{assert.doesNotMatch(fs.readFileSync('Code.gs','utf8'),/(\?\?|\|\||&&)=/);});
const c=vm.createContext({console,Date,Set,Map,JSON});for(const f of ['layout','core','delivery','offline','picking'])vm.runInContext(fs.readFileSync('src/'+f+'.js','utf8'),c);vm.runInContext('this.W=WMS;this.D=Delivery;this.O=Offline;this.P=Picking;',c);const {W,D,O,P}=c;
const ss={id:randomUUID(),name:'SK Bulk',mode:'CSFG',date:'2026-09-11',shift:'S1'},now='2026-09-11T02:00:00.000Z';
const empty=()=>({locations:c.defaultLocations_(),skus:W.SKU,stock:[],version:0});
const req=()=>({action:'bulkReceive',item:{sku:'CCN',kp:ss.date,spv:'HW',status:'Release',note:'Retur dari Distributor A'},rows:[{locationId:'CSFG C1:A1-1',qty:30,palletNo:'0031'},{locationId:'CSFG C1:B1-2',qty:18,palletNo:'125'}]});
const run=(d,r,actor=ss)=>D.mutate(d,{...r,version:d.version},actor,randomUUID,now);

const movement=d=>({action:'moveBatch',rows:d.stock.map((i,n)=>({itemId:i.id,from:i.locationId,destination:['CSFG C1:A2-1','CSFG C1:A2-3'][n]}))});
test('paired move preserves whole items, IDs, quantities and source remainder atomically',()=>{let d=run(empty(),req());d.stock.push({...d.stock[0],id:randomUUID(),palletNo:'77'});const before=JSON.stringify(d),r=movement({...d,stock:d.stock.slice(0,2)}),out=run(d,r);assert.equal(JSON.stringify(d),before);assert.deepEqual(Array.from(out.stock,i=>[i.locationId,i.qty,i.palletNo]),[['CSFG C1:A2-1',30,'31'],['CSFG C1:A2-3',18,'125'],['CSFG C1:A1-1',30,'77']]);for(let n=0;n<2;n++){assert.equal(out.stock[n].id,d.stock[n].id);assert.equal(out.stock[n].kp,d.stock[n].kp);}assert.equal(out.version,d.version+1);});
test('paired move rejects invalid second targets, duplicate items, stale origin and foreign items without partial writes',()=>{const d=run(empty(),req()),before=JSON.stringify(d);for(const patch of [{destination:'CSFG C1:A2-1'},{destination:d.stock[0].locationId},{destination:'WIP-CSFG'},{destination:'CHILLER C1:A1-1'},{destination:'missing'},{from:'CSFG C1:A9-1'},{itemId:d.stock[0].id},{itemId:randomUUID()}]){const r=movement(d);Object.assign(r.rows[1],patch);assert.throws(()=>run(d,r));assert.equal(JSON.stringify(d),before);}assert.throws(()=>run(d,{action:'moveBatch',rows:[]}));assert.throws(()=>run(d,{action:'moveBatch',rows:Array(101).fill(movement(d).rows[0])}));});
test('move updates every open allocation location and revision, preserves issued history and remains issuable',()=>{let d=run(empty(),req());const itemId=d.stock[0].id,a=randomUUID(),b=randomUUID();for(const [id,qty] of [[a,12],[b,10]])d=run(d,{action:'saveDelivery',documentId:id,documentRevision:0,date:ss.date,destination:'Truk',lines:[{itemId,qty}]});const history={...JSON.parse(JSON.stringify(d.deliveryNotes[0])),id:randomUUID(),state:'ISSUED'};d.deliveryNotes.push(history);const oldHistory=JSON.stringify(history);d=run(d,movement(d));assert.equal(D.availability(d,itemId).reserved,22);for(const id of [a,b]){assert.equal(D.find(d,id).lines[0].location,'A2-1');assert.equal(D.find(d,id).revision,2);}assert.equal(JSON.stringify(d.deliveryNotes[2]),oldHistory);d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:a,documentRevision:2});d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:b,documentRevision:2});assert.equal(d.stock.find(i=>i.id===itemId).qty,8);});
test('moving cannot silently fix a stale QC/product snapshot in a draft',()=>{let d=run(empty(),req()),id=randomUUID();d=run(d,{action:'saveDelivery',documentId:id,documentRevision:0,date:ss.date,destination:'Truk',lines:[{itemId:d.stock[0].id,qty:12}]});d.stock[0].status='Hold';d=run(d,movement(d));assert.equal(D.find(d,id).lines[0].status,'Release');assert.throws(()=>run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:id,documentRevision:2}),/berubah/);});
test('paired move outbox fingerprints sources, targets and affected drafts, survives reload and exact acknowledgement',()=>{let d=run(empty(),req());d=run(d,{action:'saveDelivery',documentId:randomUUID(),documentRevision:0,date:ss.date,destination:'Truk',lines:[{itemId:d.stock[0].id,qty:12}]});const state=O.enqueue(O.initial(d),{...movement(d),version:d.version},ss,randomUUID,now);assert.equal(state.queue.length,1);assert.equal(Object.keys(state.queue[0].expected).length,5);const restored=JSON.parse(JSON.stringify(state)),server=O.apply(d,restored.queue[0],ss);assert.equal(JSON.stringify(server),JSON.stringify(state.data));const frozen=O.freeze(restored,randomUUID),ack=O.acknowledge(frozen,{batchId:frozen.inflight.id,ackIds:[frozen.queue[0].id],data:server});assert.equal(ack.queue.length,0);assert.equal(ack.data.deliveryNotes[0].lines[0].location,'A2-1');});
test('short KP searches retain full-year FEFO order and separate summary groups',()=>{const d=run(empty(),req());d.stock[0].kp='2026-09-12';d.stock[1].kp='2025-09-12';const matches=P.candidates(d,'CSFG',{query:'12.09',fefo:true});assert.deepEqual(Array.from(matches,i=>i.kp),['2025-09-12','2026-09-12']);assert.equal(P.summary(matches).length,2);assert.equal(W.short('2026-09-12'),'12.09');});
test('bulk receipt creates independently numbered quantities with shared return notes, no partial mutation',()=>{const before=empty(),d=run(before,req());assert.equal(before.stock.length,0);assert.equal(d.version,1);assert.deepEqual(Array.from(d.stock,i=>[i.palletNo,i.qty]),[['31',30],['125',18]]);assert(d.stock.every(i=>i.note==='Retur dari Distributor A'&&i.unit==='CTN'&&i.spv==='HW'));assert.notEqual(d.stock[0].id,d.stock[1].id);});
test('invalid last bulk row rejects whole receipt including earlier valid rows',()=>{for(const patch of [{qty:0},{qty:1.5},{palletNo:'1x'},{locationId:'CSFG C1:A1-1'},{locationId:'CSFG C2:A3-1'},{locationId:'CHILLER C1:A1-1'},{locationId:'WIP-CSFG'},{locationId:'missing'}]){const d=empty(),r=req();Object.assign(r.rows[1],patch);assert.throws(()=>run(d,r));assert.equal(d.stock.length,0);assert.equal(d.version,0);}});
test('occupied bulk rack rejects entire operation, including empty first rack',()=>{const d=run(empty(),req()),r=req();r.rows[0].locationId='CSFG C1:A2-1';assert.throws(()=>run(d,r),/sudah terisi/);assert.equal(d.stock.length,2);assert(!d.stock.some(i=>i.locationId==='CSFG C1:A2-1'));});
test('bulk validates common fields, size and IDs',()=>{for(const patch of [{spv:''},{sku:'BG'},{kp:'2026-02-30'},{status:'Retur'}]){const r=req();Object.assign(r.item,patch);assert.throws(()=>run(empty(),r));}for(const rows of [[],Array(101).fill(req().rows[0])])assert.throws(()=>run(empty(),{...req(),rows}));const r=req(),id=randomUUID();r.rows.forEach(x=>x.id=id);assert.throws(()=>run(empty(),r),/duplikat/);});
test('bulk CHILLER uses ordinary status and expiry, preserves non-commercial location function',()=>{const d=empty(),loc=d.locations.find(l=>l.kind==='rack'&&l.group==='CHILLER');loc.functionType=W.FUNCTIONS[1];const r=req();r.item={...r.item,sku:'BG',status:'GR'};r.rows=[{locationId:loc.id,qty:48,palletNo:'999'}];const out=run(d,r,{...ss,mode:'CHILLER'});assert.equal(out.stock[0].spv,'');assert.equal(out.stock[0].exp,W.expiry(ss.date,180));assert.equal(out.locations.find(l=>l.id===loc.id).functionType,W.FUNCTIONS[1]);});
test('bulk durable outbox assigns stable IDs and covers every target, replays and acknowledges together',()=>{const initial=empty(),r=req();let state=O.enqueue(O.initial(initial),{...r,version:0},ss,randomUUID,now);assert.equal(state.queue.length,1);assert.equal(Object.keys(state.queue[0].expected).length,2);const restored=JSON.parse(JSON.stringify(state)),server=O.apply(initial,restored.queue[0],ss);assert.equal(JSON.stringify(server.stock),JSON.stringify(state.data.stock));state=O.freeze(state,randomUUID);const ack=O.acknowledge(state,{batchId:state.inflight.id,ackIds:[state.queue[0].id],data:server});assert.equal(ack.queue.length,0);assert.equal(ack.data.stock.length,2);});
test('KP FEFO groups products, orders Release oldest first and keeps Hold visible without selecting stock',()=>{const d=run(empty(),req()),base=d.stock[0];d.stock=[{...base,id:'hold',status:'Hold',kp:'2020-01-01'},{...base,id:'new',kp:'2026-09-11'},{...base,id:'old',kp:'2026-09-01'},{...base,id:'other',sku:'PCN',kp:'2020-01-01'}];const before=JSON.stringify(d);assert.deepEqual(Array.from(P.candidates(d,'CSFG',{fefo:true}),i=>i.id),['old','new','hold','other']);assert.deepEqual(Array.from(P.candidates(d,'CSFG',{fefo:true,sku:'CCN',query:'Hold'}),i=>i.id),['hold']);assert.equal(JSON.stringify(d),before);assert.equal(P.candidates(d,'CHILLER',{fefo:true}).length,0);});
test('normalization accepts hundreds and preserves long legacy digits without precision loss',()=>{for(const [a,b] of [['0031','31'],['125','125'],['999','999'],['000','0'],['',''],['00123456789012345678','123456789012345678']])assert.equal(W.pallet(a),b);const r=req();r.rows[0].palletNo='12345678901234567890';assert.equal(run(empty(),r).stock[0].palletNo,'12345678901234567890');});
test('legacy padded pallet on a saved draft remains issuable after equivalent normalization',()=>{let d=run(empty(),req());const id=randomUUID();d=run(d,{action:'saveDelivery',documentId:id,documentRevision:0,date:ss.date,destination:'Packing',note:'',lines:[{itemId:d.stock[0].id,qty:3}]});d.deliveryNotes[0].lines[0].palletNo='0031';const out=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:id,documentRevision:1});assert.equal(out.stock[0].qty,27);assert.match(D.text(out.deliveryNotes[0]),/Pallet 31/);assert.equal(out.deliveryNotes[0].lines[0].palletNo,'0031');});

test('picking summary merges racks and pallets but separates product, KP and legacy units',()=>{const lines=[{sku:'CCN',kp:'2026-09-08',qty:'7',unit:'CTN',palletNo:'31'},{sku:'CCN',kp:'2026-09-08',qty:18,unit:'CTN',palletNo:'125'},{sku:'CCN',kp:'2026-09-09',qty:30,unit:'CTN'},{sku:'PCN',kp:'2026-09-08',qty:11,unit:'CTN'},{sku:'CCN',kp:'2026-09-08',qty:2,unit:'PACK'}];const original=JSON.stringify(lines);assert.deepEqual(JSON.parse(JSON.stringify(P.summary(lines))),[{sku:'CCN',kp:'2026-09-08',unit:'CTN',qty:25,pallets:2},{sku:'CCN',kp:'2026-09-08',unit:'PACK',qty:2,pallets:1},{sku:'CCN',kp:'2026-09-09',unit:'CTN',qty:30,pallets:1},{sku:'PCN',kp:'2026-09-08',unit:'CTN',qty:11,pallets:1}]);assert.equal(JSON.stringify(lines),original);});

test('one shift supports multiple truck picks without reducing physical stock; issuing only reduces its own lines',()=>{let d=run(empty(),req());const a=randomUUID(),b=randomUUID();for(const [id,truck,qty] of [[a,'B 1234 AB',7],[b,'B 5678 CD',9]])d=run(d,{action:'saveDelivery',documentId:id,documentRevision:0,date:ss.date,shift:'S1',truck,destination:'Packing',lines:[{itemId:d.stock[0].id,qty}]});assert.equal(d.stock[0].qty,30);assert.equal(d.deliveryNotes.length,2);const first=D.find(d,a);assert.equal(first.shift,'S1');assert.match(first.pickingNumber,/^PL-/);assert.notEqual(first.pickingNumber,D.find(d,b).pickingNumber);assert.match(D.text(first,'picking'),/B 1234 AB/);assert.match(D.text(first,'picking'),/PICKING LIST/);d=run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:a,documentRevision:1});assert.equal(d.stock[0].qty,23);assert.equal(D.find(d,b).state,'DRAFT');assert.throws(()=>run(d,{action:'issueDelivery',sjNumber:'0000123456',documentId:a,documentRevision:2}));assert.equal(d.stock[0].qty,23);});

test('new truck picks require a truck and valid shift before any mutation',()=>{const initial=run(empty(),req());for(const bad of [{truck:''},{shift:'S4'},{truck:'x'.repeat(81)}])assert.throws(()=>run(initial,{action:'saveDelivery',documentId:randomUUID(),documentRevision:0,date:ss.date,shift:'S1',truck:'Truk 1',destination:'Packing',lines:[{itemId:initial.stock[0].id,qty:7}],...bad}));assert.equal(initial.deliveryNotes,undefined);assert.equal(initial.stock[0].qty,30);});
